/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int xMouse, yMouse;

    public DashBoard(String x) {
        initComponents();
        this.setLocationRelativeTo(this);      
                 txtNivel.setText(x);
        
        FrmPrincipal p1 = new FrmPrincipal();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JPanel();
        jlbMinimize = new javax.swing.JLabel();
        txtExit = new javax.swing.JPanel();
        jlbExit = new javax.swing.JLabel();
        Part = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JPanel();
        txtNivel = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuLateral = new javax.swing.JPanel();
        txtTitulo1 = new javax.swing.JLabel();
        btnPrin = new javax.swing.JPanel();
        txPrinLeft = new javax.swing.JLabel();
        btnNuevaVentaLeft = new javax.swing.JPanel();
        txtNuevaVentaLeft = new javax.swing.JLabel();
        btnClienteLeft = new javax.swing.JPanel();
        txtClienteLeft = new javax.swing.JLabel();
        btnProductoLeft = new javax.swing.JPanel();
        txtProductoLeft = new javax.swing.JLabel();
        btnProveedorLeft = new javax.swing.JPanel();
        txtProveedorLeft = new javax.swing.JLabel();
        btnReporte = new javax.swing.JPanel();
        txtVentaLeft = new javax.swing.JLabel();
        btnConfigLeft = new javax.swing.JPanel();
        txtConfigLeft = new javax.swing.JLabel();
        textLogoEmpresa = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1270, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setBackground(new java.awt.Color(171, 161, 120));
        txtTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txtTituloMouseDragged(evt);
            }
        });
        txtTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTituloMousePressed(evt);
            }
        });
        txtTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(171, 161, 120));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimize.setBackground(new java.awt.Color(170, 160, 120));

        jlbMinimize.setBackground(new java.awt.Color(170, 160, 120));
        jlbMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/7752934_minimize_ui_basic_interface_icon.png"))); // NOI18N
        jlbMinimize.setToolTipText("");
        jlbMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbMinimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMinimizeLayout = new javax.swing.GroupLayout(btnMinimize);
        btnMinimize.setLayout(btnMinimizeLayout);
        btnMinimizeLayout.setHorizontalGroup(
            btnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMinimizeLayout.createSequentialGroup()
                .addGap(581, 581, 581)
                .addComponent(jlbMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnMinimizeLayout.setVerticalGroup(
            btnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(btnMinimizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        jPanel3.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 0, 40, -1));

        txtExit.setBackground(new java.awt.Color(170, 160, 120));

        jlbExit.setBackground(new java.awt.Color(170, 160, 120));
        jlbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/4115230_cancel_close_delete_icon.png"))); // NOI18N
        jlbExit.setToolTipText("");
        jlbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout txtExitLayout = new javax.swing.GroupLayout(txtExit);
        txtExit.setLayout(txtExitLayout);
        txtExitLayout.setHorizontalGroup(
            txtExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtExitLayout.createSequentialGroup()
                .addComponent(jlbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        txtExitLayout.setVerticalGroup(
            txtExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 40, 40));

        txtTitulo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 200, -1));

        Part.setBackground(new java.awt.Color(123, 120, 108));

        javax.swing.GroupLayout PartLayout = new javax.swing.GroupLayout(Part);
        Part.setLayout(PartLayout);
        PartLayout.setHorizontalGroup(
            PartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        PartLayout.setVerticalGroup(
            PartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        txtTitulo.add(Part, new org.netbeans.lib.awtextra.AbsoluteConstraints(986, 0, 50, -1));

        btnAdmin.setBackground(new java.awt.Color(171, 161, 120));
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminMouseExited(evt);
            }
        });

        txtNivel.setBackground(new java.awt.Color(171, 161, 120));
        txtNivel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 10)); // NOI18N
        txtNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_male_user_20px.png"))); // NOI18N
        txtNivel.setText("ADMIN");

        javax.swing.GroupLayout btnAdminLayout = new javax.swing.GroupLayout(btnAdmin);
        btnAdmin.setLayout(btnAdminLayout);
        btnAdminLayout.setHorizontalGroup(
            btnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        btnAdminLayout.setVerticalGroup(
            btnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAdminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtTitulo.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 0, 190, -1));

        btnCerrar.setBackground(new java.awt.Color(199, 192, 165));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/3005766_account_door_exit_logout_icon.png"))); // NOI18N
        jLabel1.setText("CERRAR SESIÓN");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarLayout = new javax.swing.GroupLayout(btnCerrar);
        btnCerrar.setLayout(btnCerrarLayout);
        btnCerrarLayout.setHorizontalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCerrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnCerrarLayout.setVerticalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtTitulo.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 230, 40));

        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1070, 40));

        MenuLateral.setBackground(new java.awt.Color(185, 180, 163));
        MenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo1.setBackground(new java.awt.Color(135, 121, 86));
        txtTitulo1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        txtTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo1.setText("Inversiones D y E");
        txtTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtTitulo1.setOpaque(true);
        MenuLateral.add(txtTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        btnPrin.setBackground(new java.awt.Color(208, 205, 193));
        btnPrin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrin.setPreferredSize(new java.awt.Dimension(200, 36));
        btnPrin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrinMousePressed(evt);
            }
        });
        btnPrin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txPrinLeft.setBackground(new java.awt.Color(185, 180, 163));
        txPrinLeft.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txPrinLeft.setText("PRINCIPAL");
        btnPrin.add(txPrinLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        MenuLateral.add(btnPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 40));

        btnNuevaVentaLeft.setBackground(new java.awt.Color(185, 180, 163));
        btnNuevaVentaLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevaVentaLeft.setPreferredSize(new java.awt.Dimension(200, 36));
        btnNuevaVentaLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevaVentaLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevaVentaLeftMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNuevaVentaLeftMousePressed(evt);
            }
        });
        btnNuevaVentaLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNuevaVentaLeft.setBackground(new java.awt.Color(185, 180, 163));
        txtNuevaVentaLeft.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtNuevaVentaLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_checkout_26px_2.png"))); // NOI18N
        txtNuevaVentaLeft.setText("NUEVA VENTA");
        btnNuevaVentaLeft.add(txtNuevaVentaLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        MenuLateral.add(btnNuevaVentaLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 293, -1, 40));

        btnClienteLeft.setBackground(new java.awt.Color(185, 180, 163));
        btnClienteLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClienteLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClienteLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClienteLeftMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClienteLeftMousePressed(evt);
            }
        });
        btnClienteLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtClienteLeft.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtClienteLeft.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtClienteLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_customer_26px_1.png"))); // NOI18N
        txtClienteLeft.setText("CLIENTE");
        btnClienteLeft.add(txtClienteLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        MenuLateral.add(btnClienteLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 333, 200, 40));

        btnProductoLeft.setBackground(new java.awt.Color(185, 180, 163));
        btnProductoLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductoLeft.setPreferredSize(new java.awt.Dimension(200, 36));
        btnProductoLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductoLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductoLeftMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProductoLeftMousePressed(evt);
            }
        });
        btnProductoLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProductoLeft.setBackground(new java.awt.Color(185, 180, 163));
        txtProductoLeft.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtProductoLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_product_26px.png"))); // NOI18N
        txtProductoLeft.setText("PRODUCTO");
        btnProductoLeft.add(txtProductoLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -4, 107, 40));

        MenuLateral.add(btnProductoLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        btnProveedorLeft.setBackground(new java.awt.Color(185, 180, 163));
        btnProveedorLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProveedorLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProveedorLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProveedorLeftMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProveedorLeftMousePressed(evt);
            }
        });
        btnProveedorLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProveedorLeft.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtProveedorLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_worker_26px.png"))); // NOI18N
        txtProveedorLeft.setText("PROVEEDOR");
        btnProveedorLeft.add(txtProveedorLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        MenuLateral.add(btnProveedorLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 200, 40));

        btnReporte.setBackground(new java.awt.Color(185, 180, 163));
        btnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReporteMousePressed(evt);
            }
        });
        btnReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtVentaLeft.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtVentaLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_bill_26px.png"))); // NOI18N
        txtVentaLeft.setText("REPORTES");
        btnReporte.add(txtVentaLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        MenuLateral.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 200, 40));

        btnConfigLeft.setBackground(new java.awt.Color(185, 180, 163));
        btnConfigLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfigLeftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfigLeftMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConfigLeftMousePressed(evt);
            }
        });
        btnConfigLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtConfigLeft.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        txtConfigLeft.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtConfigLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_open_end_wrench_24px.png"))); // NOI18N
        txtConfigLeft.setText("CONFIGURACIÓN");
        btnConfigLeft.add(txtConfigLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        MenuLateral.add(btnConfigLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 626, 200, 40));
        MenuLateral.add(textLogoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 110));

        jPanel1.add(MenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 670));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 1070, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jlbExitMouseClicked

    private void jlbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbExitMouseEntered
        // TODO add your handling code here:
        txtExit.setBackground(Color.red);
    }//GEN-LAST:event_jlbExitMouseEntered

    private void jlbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbExitMouseExited
        // TODO add your handling code here:
        txtExit.setBackground(new Color(170, 160, 120));
    }//GEN-LAST:event_jlbExitMouseExited

    private void txtTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTituloMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_txtTituloMouseDragged

    private void txtTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTituloMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_txtTituloMousePressed

    private void btnNuevaVentaLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaVentaLeftMouseExited
        // TODO add your handling code here:
        /*if(btnPrin.getBackground().getRGB() != -15574355 || btnClienteLeft.getBackground().getRGB() != -15574355
             || btnProductoLeft.getBackground().getRGB() != -15574355 || btnProductoLeft.getBackground().getRGB() != -15574355 || btnVentaLeft.getBackground().getRGB() != -15574355
                || btnConfigLeft.getBackground().getRGB() != -15574355)
            resetColor(btnNuevaVentaLeft);*/
    }//GEN-LAST:event_btnNuevaVentaLeftMouseExited

    private void btnNuevaVentaLeftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaVentaLeftMousePressed
        // TODO add your handling code here
        resetColor(btnPrin);
        setColor(btnNuevaVentaLeft);
        resetColor(btnClienteLeft);
        resetColor(btnProductoLeft);
        resetColor(btnProveedorLeft);
        resetColor(btnReporte);
        resetColor(btnConfigLeft);
        // Abrir sección
        FrmNuevaVenta p1 = new FrmNuevaVenta();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnNuevaVentaLeftMousePressed

    private void btnClienteLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteLeftMouseEntered
        /*if(btnClienteLeft.getBackground().getRGB() == -15574355)
            setColor(btnClienteLeft);
        btnClienteLeft.setBackground(new Color(208,205,193));*/
    }//GEN-LAST:event_btnClienteLeftMouseEntered

    private void btnClienteLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteLeftMouseExited
       /* if(btnPrin.getBackground().getRGB() != -15574355 || btnNuevaVentaLeft.getBackground().getRGB() != -15574355
             || btnProductoLeft.getBackground().getRGB() != -15574355 || btnProveedorLeft.getBackground().getRGB() != -15574355 || btnVentaLeft.getBackground().getRGB() != -15574355
                || btnConfigLeft.getBackground().getRGB() != -15574355)
            resetColor(btnClienteLeft);
       btnClienteLeft.setBackground(new Color(185,180,163));*/
    }//GEN-LAST:event_btnClienteLeftMouseExited

    private void btnNuevaVentaLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaVentaLeftMouseEntered
       /* if(btnNuevaVentaLeft.getBackground().getRGB() == -15574355)
            setColor(btnNuevaVentaLeft);*/
       
    }//GEN-LAST:event_btnNuevaVentaLeftMouseEntered

    private void btnPrinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrinMouseEntered
        // TODO add your handling code here:
         /*if(btnPrin.getBackground().getRGB() == -12343211)
            setColor(btnPrin);*/
    }//GEN-LAST:event_btnPrinMouseEntered

    private void btnPrinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrinMouseExited
        // TODO add your handling code here:
       /* if(btnNuevaVentaLeft.getBackground().getRGB() != -15574355 || btnClienteLeft.getBackground().getRGB() != -15574355
            || btnProductoLeft.getBackground().getRGB() != -15574355 || btnProveedorLeft.getBackground().getRGB() != -15574355 || btnVentaLeft.getBackground().getRGB() != -15574355
                || btnConfigLeft.getBackground().getRGB() != -15574355)
            resetColor(btnPrin);*/
       
        
    }//GEN-LAST:event_btnPrinMouseExited

    private void btnPrinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrinMousePressed
        // TODO add your handling code here:
        setColor(btnPrin);
        resetColor(btnNuevaVentaLeft);
        resetColor(btnClienteLeft);
        resetColor(btnProductoLeft);
        resetColor(btnProveedorLeft);
        resetColor(btnReporte);
        resetColor(btnConfigLeft);
        // Abrir sección
        FrmPrincipal p1 = new FrmPrincipal();
        p1.setSize(1080, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }//GEN-LAST:event_btnPrinMousePressed

    private void btnClienteLeftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteLeftMousePressed
        // TODO add your handling code here:
     //   private void btnClienteLeftMouseExited(java.awt.event.MouseEvent evt) {        
        resetColor(btnPrin);
        resetColor(btnNuevaVentaLeft);
        setColor(btnClienteLeft);
        resetColor(btnProductoLeft);
        resetColor(btnProveedorLeft);
        resetColor(btnReporte);
        resetColor(btnConfigLeft);
        // Abrir sección
        FrmCliente p1 = new FrmCliente();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    
    }//GEN-LAST:event_btnClienteLeftMousePressed

    private void btnProductoLeftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoLeftMousePressed
        // TODO add your handling code here:
        resetColor(btnPrin);
        resetColor(btnNuevaVentaLeft);
        resetColor(btnClienteLeft);
        setColor(btnProductoLeft);
        resetColor(btnProveedorLeft);
        resetColor(btnReporte);
        resetColor(btnConfigLeft);
        // Abrir sección
        FrmProducto1 p1 = new FrmProducto1();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnProductoLeftMousePressed

    private void btnProductoLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoLeftMouseExited
        // TODO add your handling code here:
       /*if(btnPrin.getBackground().getRGB() != -15574355 || btnNuevaVentaLeft.getBackground().getRGB() != -15574355
            || btnClienteLeft.getBackground().getRGB() != -15574355 || btnProveedorLeft.getBackground().getRGB() != -15574355 ||  btnVentaLeft.getBackground().getRGB() != -15574355
                || btnConfigLeft.getBackground().getRGB() != -15574355)
            resetColor(btnProductoLeft);*/
        
    }//GEN-LAST:event_btnProductoLeftMouseExited

    private void btnProductoLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoLeftMouseEntered
        // TODO add your handling code here:
       /* if(btnProductoLeft.getBackground().getRGB() == -15574355)
            setColor(btnProductoLeft);*/
    }//GEN-LAST:event_btnProductoLeftMouseEntered

    private void btnProveedorLeftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedorLeftMousePressed
        // TODO add your handling code here:
        resetColor(btnPrin);
        resetColor(btnNuevaVentaLeft);
        resetColor(btnClienteLeft);
        resetColor(btnProductoLeft);
        setColor(btnProveedorLeft);
        resetColor(btnReporte);
        resetColor(btnConfigLeft);
        // Abrir sección
        FrmProveedor p1 = new FrmProveedor();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnProveedorLeftMousePressed

    private void btnProveedorLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedorLeftMouseExited
        // TODO add your handling code here:
      /* if(btnPrin.getBackground().getRGB() != -15574355 || btnNuevaVentaLeft.getBackground().getRGB() != -15574355
             ||btnClienteLeft.getBackground().getRGB() != -15574355 || btnProductoLeft.getBackground().getRGB() != -15574355 || btnVentaLeft.getBackground().getRGB() != -15574355
                || btnConfigLeft.getBackground().getRGB() != -15574355)
            resetColor(btnProveedorLeft);*/
    }//GEN-LAST:event_btnProveedorLeftMouseExited

    private void btnProveedorLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedorLeftMouseEntered
        // TODO add your handling code here:
       /*if(btnProveedorLeft.getBackground().getRGB() == -15574355)
            setColor(btnProveedorLeft);*/
    }//GEN-LAST:event_btnProveedorLeftMouseEntered

    private void btnReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseEntered
        // TODO add your handling code here:
     /* if(btnVentaLeft.getBackground().getRGB() == -15574355)
            setColor(btnVentaLeft);*/
    }//GEN-LAST:event_btnReporteMouseEntered

    private void btnReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseExited
        // TODO add your handling code here:
      /*  if(btnPrin.getBackground().getRGB() != -15574355 || btnNuevaVentaLeft.getBackground().getRGB() != -15574355
             ||btnClienteLeft.getBackground().getRGB() != -15574355 || btnProductoLeft.getBackground().getRGB() != -15574355 || btnProveedorLeft.getBackground().getRGB() != -15574355
                || btnConfigLeft.getBackground().getRGB() != -15574355)
            resetColor(btnVentaLeft);*/
    }//GEN-LAST:event_btnReporteMouseExited

    private void btnReporteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMousePressed
        // TODO add your handling code here:
        resetColor(btnPrin);
        resetColor(btnNuevaVentaLeft);
        resetColor(btnClienteLeft);
        resetColor(btnProductoLeft);
        resetColor(btnProveedorLeft);
        setColor(btnReporte);
        resetColor(btnConfigLeft);
        // Abrir sección
        FrmReporte p1 = new FrmReporte();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnReporteMousePressed

    private void btnConfigLeftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigLeftMousePressed
        // TODO add your handling code here:
        resetColor(btnPrin);
        resetColor(btnNuevaVentaLeft);
        resetColor(btnClienteLeft);
        resetColor(btnProductoLeft);
        resetColor(btnProveedorLeft);
        resetColor(btnReporte);
        setColor(btnConfigLeft);
        // Abrir sección
        FrmConfig p1 = new FrmConfig();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnConfigLeftMousePressed

    private void btnConfigLeftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigLeftMouseExited
        // TODO add your handling code here:
    /*if(btnPrin.getBackground().getRGB() != -15574355||  btnNuevaVentaLeft.getBackground().getRGB() != -15574355
             ||btnClienteLeft.getBackground().getRGB() != -15574355  ||btnProductoLeft.getBackground().getRGB() != -15574355  ||btnProveedorLeft.getBackground().getRGB() != -15574355
                || btnVentaLeft.getBackground().getRGB() != -15574355)
            resetColor(btnConfigLeft);*/
    }//GEN-LAST:event_btnConfigLeftMouseExited

    private void btnConfigLeftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigLeftMouseEntered
        // TODO add your handling code here:
        /*if(btnConfigLeft.getBackground().getRGB() == -15574355)
            setColor(btnConfigLeft);*/
    }//GEN-LAST:event_btnConfigLeftMouseEntered

    private void btnPrinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrinMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnPrinMouseClicked

    private void jlbMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMinimizeMouseClicked
        // TODO add your handling code here:
               setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jlbMinimizeMouseClicked

    private void jlbMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMinimizeMouseEntered
        // TODO add your handling code here:
               btnMinimize.setBackground(Color.gray);
               
    }//GEN-LAST:event_jlbMinimizeMouseEntered

    private void jlbMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMinimizeMouseExited
        // TODO add your handling code here:
              btnMinimize.setBackground(new Color(170, 160, 120));
    }//GEN-LAST:event_jlbMinimizeMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered

    }//GEN-LAST:event_jLabel1MouseEntered

    private void btnAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseClicked
        // TODO add your handling code here:
          int posicion = btnCerrar.getX();
        if(posicion >730){ 
             Animacion.Animacion.mover_izquierda(900,730 , 2, 2, btnCerrar);  
             Animacion.Animacion.mover_izquierda(1031, 860, 2, 2, Part);
    
        }else{     
            Animacion.Animacion.mover_derecha(730, 900, 2, 2, btnCerrar); 
            Animacion.Animacion.mover_derecha(860,1031 , 2, 2, Part);
        }
    }//GEN-LAST:event_btnAdminMouseClicked

    private void btnAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseEntered
        // TODO add your handling code here:
        btnAdmin.setBackground(new Color(199,192,165));
    }//GEN-LAST:event_btnAdminMouseEntered

    private void btnAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseExited
        // TODO add your handling code here:
        btnAdmin.setBackground(new Color(171,161,120));
    }//GEN-LAST:event_btnAdminMouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
               FrmLogin obj = new FrmLogin();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel1MousePressed
    void setColor(JPanel panel){
        panel.setBackground(new Color(208, 205, 193));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(185, 180, 163));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JPanel Part;
    private javax.swing.JPanel btnAdmin;
    private javax.swing.JPanel btnCerrar;
    private javax.swing.JPanel btnClienteLeft;
    private javax.swing.JPanel btnConfigLeft;
    private javax.swing.JPanel btnMinimize;
    private javax.swing.JPanel btnNuevaVentaLeft;
    private javax.swing.JPanel btnPrin;
    private javax.swing.JPanel btnProductoLeft;
    private javax.swing.JPanel btnProveedorLeft;
    private javax.swing.JPanel btnReporte;
    public static javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlbExit;
    private javax.swing.JLabel jlbMinimize;
    private javax.swing.JLabel textLogoEmpresa;
    private javax.swing.JLabel txPrinLeft;
    private javax.swing.JLabel txtClienteLeft;
    private javax.swing.JLabel txtConfigLeft;
    private javax.swing.JPanel txtExit;
    private javax.swing.JLabel txtNivel;
    private javax.swing.JLabel txtNuevaVentaLeft;
    private javax.swing.JLabel txtProductoLeft;
    private javax.swing.JLabel txtProveedorLeft;
    private javax.swing.JPanel txtTitulo;
    private javax.swing.JLabel txtTitulo1;
    private javax.swing.JLabel txtVentaLeft;
    // End of variables declaration//GEN-END:variables
}
