package Presentacion;
import BussinessObject.ClienteBO;
import BussinessObject.PersonaBO;
import DataTransferObject.ClienteDTO;
import DataTransferObject.PersonaDTO;
import Implementacion.IDaoGeneral;
import static Presentacion.DashBoard.content;
import Type.BaseDatos;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
public class FrmCliente extends javax.swing.JPanel {
    BaseDatos Gestor;
     IDaoGeneral ClienteDao;
     ClienteBO Bo;
     PersonaBO Bo2;
    public FrmCliente() {
        initComponents();
        ClienteDao = FrmLogin.dao;
        Gestor = FrmLogin.base;
        Bo = new ClienteBO(ClienteDao.ClienteClass(Gestor));
        Bo2 = new PersonaBO(ClienteDao.PersonaClass(Gestor));
        txtCodigoPersona.setText(FrmVistaCliente1.IdPersona);
        txtCodigoCliente.setText(FrmVistaCliente1.IdCliente);
        cbxTipoDocumento.setSelectedItem(FrmVistaCliente1.TipoD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        btnNuevoCl = new javax.swing.JButton();
        btnGuardarCl = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminarCl = new javax.swing.JButton();
        btnSalirCl = new javax.swing.JButton();
        btnModificarCl1 = new javax.swing.JButton();
        Text4 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JTextField();
        text5 = new javax.swing.JLabel();
        text9 = new javax.swing.JLabel();
        text8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text10 = new javax.swing.JLabel();
        text11 = new javax.swing.JLabel();
        text12 = new javax.swing.JLabel();
        text13 = new javax.swing.JLabel();
        txtNumeroCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        txtCodigoPersona = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        cbxTipoDocumento = new javax.swing.JComboBox<>();
        txtNumeroDoc = new javax.swing.JTextField();
        chxEstado = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        rbtMasculino = new javax.swing.JRadioButton();
        rbtFemenino = new javax.swing.JRadioButton();
        FechaInicio = new com.toedter.calendar.JDateChooser();
        FechaNac = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        jlbFondoCliente = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(167, 144, 131));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnNuevoCl.setBackground(new java.awt.Color(163, 149, 126));
        btnNuevoCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/49576_new_add_plus_user_icon.png"))); // NOI18N
        btnNuevoCl.setText("LISTAR");
        btnNuevoCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClActionPerformed(evt);
            }
        });

        btnGuardarCl.setBackground(new java.awt.Color(163, 149, 126));
        btnGuardarCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/285657_floppy_guardar_save_icon.png"))); // NOI18N
        btnGuardarCl.setText("GUARDAR");
        btnGuardarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(163, 149, 126));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/8726304_refresh_icon.png"))); // NOI18N
        btnActualizar.setText("Extraer datos");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminarCl.setBackground(new java.awt.Color(163, 149, 126));
        btnEliminarCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/352303_delete_icon.png"))); // NOI18N
        btnEliminarCl.setText("ELIMINAR");
        btnEliminarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClActionPerformed(evt);
            }
        });

        btnSalirCl.setBackground(new java.awt.Color(163, 149, 126));
        btnSalirCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/8725805_exit_icon.png"))); // NOI18N
        btnSalirCl.setText("SALIR");
        btnSalirCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirClActionPerformed(evt);
            }
        });

        btnModificarCl1.setBackground(new java.awt.Color(163, 149, 126));
        btnModificarCl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/8726304_refresh_icon.png"))); // NOI18N
        btnModificarCl1.setText("Actualizar Datos");
        btnModificarCl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCl1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarCl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoCl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnModificarCl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalirCl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 34, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 410, 140));

        Text4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text4.setForeground(new java.awt.Color(255, 255, 255));
        Text4.setText("FECHA DE INICIO");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        Text3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setText("NOMBRE");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("CÓDIGO");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FECHA DE NACIMIENTO");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("INGRESE EL NOMBRE");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 280, -1));

        txtObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(102, 102, 102));
        txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
        txtObservaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtObservacionesMousePressed(evt);
            }
        });
        txtObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacionesActionPerformed(evt);
            }
        });
        add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 250, -1));

        text5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text5.setForeground(new java.awt.Color(255, 255, 255));
        text5.setText("TIPO DE DOCUMENTO");
        add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        text9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text9.setForeground(new java.awt.Color(255, 255, 255));
        text9.setText("NÚMERO DE DOC.");
        add(text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        text8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text8.setForeground(new java.awt.Color(255, 255, 255));
        text8.setText("ESTADO");
        add(text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("N° DE PERSONA");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        text10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text10.setForeground(new java.awt.Color(255, 255, 255));
        text10.setText("CELULAR");
        add(text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        text11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text11.setForeground(new java.awt.Color(255, 255, 255));
        text11.setText("CORREO");
        add(text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        text12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text12.setForeground(new java.awt.Color(255, 255, 255));
        text12.setText("DIRECCIÓN");
        add(text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        text13.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text13.setForeground(new java.awt.Color(255, 255, 255));
        text13.setText("OBSERVACIONES");
        add(text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));

        txtNumeroCelular.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNumeroCelular.setForeground(new java.awt.Color(102, 102, 102));
        txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
        txtNumeroCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroCelularMousePressed(evt);
            }
        });
        txtNumeroCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCelularActionPerformed(evt);
            }
        });
        add(txtNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 280, -1));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreo.setText("INGRESE EL CORREO");
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 280, -1));

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion.setText("INGRESE LA DIRECCIÓN");
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionMousePressed(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 250, -1));

        txtCodigoCliente.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCodigoCliente.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoCliente.setText("Click para obtener codigo");
        txtCodigoCliente.setEnabled(false);
        txtCodigoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoClienteMousePressed(evt);
            }
        });
        txtCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoClienteActionPerformed(evt);
            }
        });
        add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 160, -1));

        txtCodigoPersona.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCodigoPersona.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoPersona.setText("Click ");
        txtCodigoPersona.setEnabled(false);
        txtCodigoPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoPersonaMousePressed(evt);
            }
        });
        add(txtCodigoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 90, 20));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setText("INGRESE LOS APELLIDOS");
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 280, -1));

        cbxTipoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DNI", "CARNET DE EXTRANJERIA", "PASAPORTE" }));
        cbxTipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxTipoDocumentoMousePressed(evt);
            }
        });
        add(cbxTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 160, -1));

        txtNumeroDoc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNumeroDoc.setForeground(new java.awt.Color(102, 102, 102));
        txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
        txtNumeroDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroDocMousePressed(evt);
            }
        });
        add(txtNumeroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, -1));

        chxEstado.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        chxEstado.setForeground(new java.awt.Color(255, 255, 255));
        chxEstado.setText("ACTIVO");
        add(chxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        jPanel2.setBackground(new java.awt.Color(167, 144, 131));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "SEXO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        rbtMasculino.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbtMasculino.setForeground(new java.awt.Color(102, 102, 102));
        rbtMasculino.setText("Masculino");

        rbtFemenino.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbtFemenino.setForeground(new java.awt.Color(102, 102, 102));
        rbtFemenino.setText("Femenino");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtMasculino)
                .addGap(18, 18, 18)
                .addComponent(rbtFemenino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMasculino)
                    .addComponent(rbtFemenino))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 190, 60));

        FechaInicio.setDateFormatString("dd/MM/yyyy");
        add(FechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 160, -1));

        FechaNac.setDateFormatString("dd/MM/yyyy");
        add(FechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 160, -1));

        jSeparator1.setBackground(new java.awt.Color(235, 224, 179));
        jSeparator1.setForeground(new java.awt.Color(235, 224, 179));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 20, 230));

        jSeparator2.setBackground(new java.awt.Color(235, 224, 179));
        jSeparator2.setForeground(new java.awt.Color(235, 224, 179));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 20, 230));

        Text5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text5.setForeground(new java.awt.Color(255, 255, 255));
        Text5.setText("APELLIDOS");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jlbFondoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente_1.png"))); // NOI18N
        add(jlbFondoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void txtObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionesActionPerformed

    private void txtNumeroCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCelularActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCodigoClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoClienteMousePressed
        // TODO add your handling code here:
        txtCodigoCliente.setText(this.CodigoCliente(txtNumeroDoc.getText().substring(0, 6)));
        if (String.valueOf(txtCodigoCliente.getText()).equals("INGRESE EL CÓDIGO")) {
            txtCodigoCliente.setText("");
            txtCodigoCliente.setForeground(Color.black);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }       
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }
 
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE EL NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
         if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
          if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
          
    }//GEN-LAST:event_txtCodigoClienteMousePressed

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void cbxTipoDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxTipoDocumentoMousePressed
        // TODO add your handling code here:
        txtNumeroDoc.setVisible(true);
    }//GEN-LAST:event_cbxTipoDocumentoMousePressed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNombre.getText()).equals("INGRESE EL NOMBRE")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        if (txtCodigoCliente.getText().isEmpty()) {
            txtCodigoCliente.setText("INGRESE EL CÓDIGO");
            txtCodigoCliente.setForeground(Color.gray);
        }       
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
         if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
          if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtApellido.getText()).equals("INGRESE LOS APELLIDOS")) {
            txtApellido.setText("");
            txtApellido.setForeground(Color.black);
        }
        if (txtCodigoCliente.getText().isEmpty()) {
            txtCodigoCliente.setText("INGRESE EL CÓDIGO");
            txtCodigoCliente.setForeground(Color.gray);
        }       
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
         if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
          if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtNumeroDocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroDocMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNumeroDoc.getText()).equalsIgnoreCase("INGRESE NUMERO DE DOC.")) {
            txtNumeroDoc.setText("");
            txtNumeroDoc.setForeground(Color.black);
        }
        if (txtCodigoCliente.getText().isEmpty()) {
            txtCodigoCliente.setText("INGRESE EL CÓDIGO");
            txtCodigoCliente.setForeground(Color.gray);
        }       
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
         if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
          if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNumeroDocMousePressed

    private void txtNumeroCelularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroCelularMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNumeroCelular.getText()).equals("INGRESE EL NÚMERO DE CEL.")) {
            txtNumeroCelular.setText("");
            txtNumeroCelular.setForeground(Color.black);
        }
        if (txtCodigoCliente.getText().isEmpty()) {
            txtCodigoCliente.setText("INGRESE EL CÓDIGO");
            txtCodigoCliente.setForeground(Color.gray);
        }       
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
         if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
          if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNumeroCelularMousePressed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtCorreo.getText()).equals("INGRESE EL CORREO")) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
        if (txtCodigoCliente.getText().isEmpty()) {
            txtCodigoCliente.setText("INGRESE EL CÓDIGO");
            txtCodigoCliente.setForeground(Color.gray);
        }       
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }
 
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
         if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
          if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtDireccion.getText()).equals("INGRESE LA DIRECCIÓN")) {
            txtDireccion.setText("");
            txtDireccion.setForeground(Color.black);
        }
        if (txtCodigoCliente.getText().isEmpty()) {
            txtCodigoCliente.setText("INGRESE EL CÓDIGO");
            txtCodigoCliente.setForeground(Color.gray);
        }       
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
         if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
          if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDireccionMousePressed

    private void txtObservacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtObservacionesMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtObservaciones.getText()).equals("INGRESE LA OBSERVACIÓN")) {
            txtObservaciones.setText("");
            txtObservaciones.setForeground(Color.black);
        }
        if (txtCodigoCliente.getText().isEmpty()) {
            txtCodigoCliente.setText("INGRESE EL CÓDIGO");
            txtCodigoCliente.setForeground(Color.gray);
        }       
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
         if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
          if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtObservacionesMousePressed

    private void btnGuardarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClActionPerformed
        try {
            this.AgregarCliente();
            JOptionPane.showMessageDialog(null, "Cliente agregado con exito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println("no funciona :(");
        }
    }//GEN-LAST:event_btnGuardarClActionPerformed

    private void btnNuevoClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClActionPerformed
             FrmVistaCliente1 p1 = new FrmVistaCliente1();
            p1.setSize(1070, 630);
            p1.setLocation(0, 0);

            content.removeAll();
            content.add(p1, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
    }//GEN-LAST:event_btnNuevoClActionPerformed

    private void txtCodigoPersonaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoPersonaMousePressed
        txtCodigoPersona.setText(this.CodigoPersona());
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtNumeroCelular.setText("");
        txtNumeroDoc.setText("");
        txtObservaciones.setText("");
        cbxTipoDocumento.setSelectedIndex(0);
        FechaInicio.setDate(null);
        FechaNac.setDate(null);
        rbtFemenino.setSelected(false);
        rbtMasculino.setSelected(false);
        chxEstado.setSelected(true);
        
    }//GEN-LAST:event_txtCodigoPersonaMousePressed

    private void btnSalirClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirClActionPerformed
      
    }//GEN-LAST:event_btnSalirClActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       // System.out.println(txtCodigoCliente.getText());
     System.out.println(txtCodigoPersona.getText());
     //this.BuscarPersona(txtCodigoPersona.getText());
     this.Buscar(txtCodigoCliente.getText());
     this.BuscarPersona(txtCodigoPersona.getText());
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnModificarCl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCl1ActionPerformed
 
       try {
            this.ActualizarCliente();
            JOptionPane.showMessageDialog(null, "Cliente actualizado con exito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println("no funciona :(");
        }
    }//GEN-LAST:event_btnModificarCl1ActionPerformed

    private void btnEliminarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClActionPerformed
           try {
            String x = this.Eliminar();
            String y = this.EliminarPersona();
            JOptionPane.showMessageDialog(null, x+" | "+y, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El cliente tiene ventas", "Cliente no eliminado", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarClActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaInicio;
    private com.toedter.calendar.JDateChooser FechaNac;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminarCl;
    private javax.swing.JButton btnGuardarCl;
    private javax.swing.JButton btnModificarCl1;
    private javax.swing.JButton btnNuevoCl;
    private javax.swing.JButton btnSalirCl;
    private javax.swing.JComboBox<String> cbxTipoDocumento;
    private javax.swing.JCheckBox chxEstado;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlbFondoCliente;
    private javax.swing.JRadioButton rbtFemenino;
    private javax.swing.JRadioButton rbtMasculino;
    private javax.swing.JLabel text10;
    private javax.swing.JLabel text11;
    private javax.swing.JLabel text12;
    private javax.swing.JLabel text13;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel text9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoPersona;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroCelular;
    private javax.swing.JTextField txtNumeroDoc;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
    private void Buscar(String Id){
        ClienteDTO obj = Bo.BuscarPorCodigo(Id);
        txtObservaciones.setText(obj.getObservaciones());
        FechaInicio.setDate(obj.getFechaI());
        chxEstado.setSelected(obj.getEstado().equals("Activo"));
    }
    private void BuscarPersona(String Id){
       PersonaDTO obj = Bo2.buscar(Id);
       txtNombre.setText(obj.getNombre());
       txtApellido.setText(obj.getApellido());
       txtCorreo.setText(obj.getCorreo());
       txtNumeroCelular.setText(obj.getCelular());
       txtNumeroDoc.setText(obj.getNumeroDucumento());
       FechaNac.setDate(obj.getFechaNac());
       rbtMasculino.setSelected(obj.getGenero().equals("Masculino"));
       rbtFemenino.setSelected(obj.getGenero().equals("Femenino"));
       txtDireccion.setText(obj.getDireccion());
        System.out.println(obj.getIdParametro());
       
    }
    
    private void AgregarCliente() throws Exception{
      String Mensaje1;
      String Mensaje2;
        System.out.println(txtCodigoPersona.getText());
       Mensaje2 = Bo2.Agregar(txtCodigoPersona.getText(), txtNombre.getText(), txtApellido.getText(), txtNumeroDoc.getText(), txtNumeroCelular.getText(), txtCorreo.getText(),
               this.Genero(rbtMasculino.isSelected()), FechaNac.getDate(), txtDireccion.getText(),this.ControlParametro(cbxTipoDocumento.getSelectedItem().toString()),this.Estado(chxEstado.isSelected()));
        System.out.println(Mensaje2);
      Mensaje1 = Bo.Agregar(txtCodigoCliente.getText(), txtCodigoPersona.getText(), FechaInicio.getDate(), txtObservaciones.getText(),this.Estado(chxEstado.isSelected()));
        System.out.println(Mensaje1);
    }
    private void ActualizarCliente() throws Exception {
        String Mensaje1;
        String Mensaje2;
        System.out.println(txtCodigoPersona.getText());
        Mensaje2 = Bo2.Actualizar(txtCodigoPersona.getText(), txtNombre.getText(), txtApellido.getText(), txtNumeroDoc.getText(), txtNumeroCelular.getText(), txtCorreo.getText(),
                this.Genero(rbtMasculino.isSelected()), FechaNac.getDate(), txtDireccion.getText(), this.ControlParametro(cbxTipoDocumento.getSelectedItem().toString()), this.Estado(chxEstado.isSelected()));
        System.out.println(Mensaje2);
        Mensaje1 = Bo.Actualizar(txtCodigoCliente.getText(), FechaInicio.getDate(), txtObservaciones.getText(), this.Estado(chxEstado.isSelected()));
        System.out.println(Mensaje1);
    }
    private String EliminarPersona()throws Exception{
        String Mensaje;
        Mensaje= Bo2.Eliminar(txtCodigoPersona.getText().trim());
        return Mensaje;
    }
    private String Eliminar() throws Exception {
        String Mensaje;
        Mensaje = Bo.Eliminar(txtCodigoCliente.getText().trim());
        return Mensaje;
    }
    private String CodigoPersona(){
        return Bo2.CodigoPersona();
    }
    private String CodigoCliente(String x){
        String Tipo = cbxTipoDocumento.getSelectedItem().toString().substring(0, 3);
        return Tipo+"-"+Bo.CodigoCliente(x);
    }
    private String Genero(boolean o){
        if(o){
            return "Masculino";
        }
        return "Femenino";
    }
    private String ControlParametro(String codigo) {
        if (codigo.equalsIgnoreCase("DNI")) {
            return "Parametro_01";
        } else {
            if (codigo.equalsIgnoreCase("CARNET DE EXTRANJERIA")) {
                return "Parametro_02";
            } else {
                    return "Parametro_03";
            }
        }
    }
    private String Estado(boolean o){
        if(o){
            return "Activo";
        }
        return "Inactivo";
    }
    
}
