/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import static Presentacion.DashBoard.content;

/**
 *
 * @author LENOVO
 */
public class FrmConfig extends javax.swing.JPanel {

    /**
     * Creates new form FrmConfig
     */
    public FrmConfig() {
        initComponents();
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        btnDProdConfig = new javax.swing.JPanel();
        btnDProdConfig1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnOCompraConfig = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnParametroConfig = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnUserConfig = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 224, 179));
        setPreferredSize(new java.awt.Dimension(1080, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(241, 234, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDProdConfig.setBackground(new java.awt.Color(241, 234, 204));
        btnDProdConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(btnDProdConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 170, 90));

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 1080, 140));

        btnDProdConfig1.setBackground(new java.awt.Color(235, 224, 179));
        btnDProdConfig1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDProdConfig1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDProdConfig1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDProdConfig1MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(82, 59, 46));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9044343_folder_details_icon.png"))); // NOI18N
        jLabel6.setText("DETALLE DEL PRODUCTO");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout btnDProdConfig1Layout = new javax.swing.GroupLayout(btnDProdConfig1);
        btnDProdConfig1.setLayout(btnDProdConfig1Layout);
        btnDProdConfig1Layout.setHorizontalGroup(
            btnDProdConfig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnDProdConfig1Layout.setVerticalGroup(
            btnDProdConfig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDProdConfig1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        add(btnDProdConfig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 220, 170));

        btnOCompraConfig.setBackground(new java.awt.Color(235, 224, 179));
        btnOCompraConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOCompraConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOCompraConfigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOCompraConfigMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(82, 59, 46));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/3702400_discount_label_price_sale_tag_icon.png"))); // NOI18N
        jLabel4.setText("ORDEN DE COMPRA");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout btnOCompraConfigLayout = new javax.swing.GroupLayout(btnOCompraConfig);
        btnOCompraConfig.setLayout(btnOCompraConfigLayout);
        btnOCompraConfigLayout.setHorizontalGroup(
            btnOCompraConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOCompraConfigLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        btnOCompraConfigLayout.setVerticalGroup(
            btnOCompraConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOCompraConfigLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        add(btnOCompraConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 200, 170));

        btnParametroConfig.setBackground(new java.awt.Color(235, 224, 179));
        btnParametroConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnParametroConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnParametroConfigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnParametroConfigMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(82, 59, 46));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/3209412_adjust_control_equalizer_panel_setting_icon.png"))); // NOI18N
        jLabel1.setText("PARÁMETRO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout btnParametroConfigLayout = new javax.swing.GroupLayout(btnParametroConfig);
        btnParametroConfig.setLayout(btnParametroConfigLayout);
        btnParametroConfigLayout.setHorizontalGroup(
            btnParametroConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnParametroConfigLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        btnParametroConfigLayout.setVerticalGroup(
            btnParametroConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnParametroConfigLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        add(btnParametroConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 190, 170));

        btnUserConfig.setBackground(new java.awt.Color(235, 224, 179));
        btnUserConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserConfigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUserConfigMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(82, 59, 46));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/172626_user_male_icon (1)_1.png"))); // NOI18N
        jLabel2.setText("USUARIO");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout btnUserConfigLayout = new javax.swing.GroupLayout(btnUserConfig);
        btnUserConfig.setLayout(btnUserConfigLayout);
        btnUserConfigLayout.setHorizontalGroup(
            btnUserConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserConfigLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        btnUserConfigLayout.setVerticalGroup(
            btnUserConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnUserConfigLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        add(btnUserConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 180, 170));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(164, 117, 91));
        jLabel8.setText("Agregar detalle del producto");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(164, 117, 91));
        jLabel20.setText("Agregar algún usuario");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(164, 117, 91));
        jLabel21.setText("Agregar algún parámetro");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(164, 117, 91));
        jLabel22.setText("Agregar orden de compra");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(82, 59, 46));
        jLabel3.setText("CONFIGURACIÓN");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserConfigMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserConfigMousePressed
        // TODO add your handling code here:
        setColor(btnUserConfig);
        resetColor(btnParametroConfig);
        resetColor(btnOCompraConfig);
        resetColor(btnDProdConfig);
        // Abrir sección
        FrmUsuario p1 = new FrmUsuario();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnUserConfigMousePressed

    private void btnParametroConfigMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParametroConfigMousePressed
        // TODO add your handling code here:
        resetColor(btnUserConfig);
        setColor(btnParametroConfig);
        resetColor(btnOCompraConfig);
        resetColor(btnDProdConfig);
        // Abrir sección
        FrmParametro p1 = new FrmParametro();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnParametroConfigMousePressed

    private void btnOCompraConfigMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOCompraConfigMousePressed
        // TODO add your handling code here:
        resetColor(btnUserConfig);
        resetColor(btnParametroConfig);
        setColor(btnOCompraConfig);
        resetColor(btnDProdConfig);
        // Abrir sección
        FrmPedido1 p1 = new FrmPedido1();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnOCompraConfigMousePressed

    private void btnDProdConfig1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDProdConfig1MousePressed
        // TODO add your handling code here:
        resetColor(btnUserConfig);
        resetColor(btnParametroConfig);
        resetColor(btnOCompraConfig);
        setColor(btnDProdConfig);
        // Abrir sección
        FrmDProd1 p1 = new FrmDProd1();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnDProdConfig1MousePressed

    private void btnUserConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserConfigMouseExited
        // TODO add your handling code here:
        btnUserConfig.setBackground(new Color(235,224,179));
    }//GEN-LAST:event_btnUserConfigMouseExited

    private void btnUserConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserConfigMouseEntered
        // TODO add your handling code here:
        btnUserConfig.setBackground(new Color(241, 234, 204));
    }//GEN-LAST:event_btnUserConfigMouseEntered

    private void btnParametroConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParametroConfigMouseExited
        // TODO add your handling code here:
        btnParametroConfig.setBackground(new Color(235,224,179));
    }//GEN-LAST:event_btnParametroConfigMouseExited

    private void btnParametroConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParametroConfigMouseEntered
        // TODO add your handling code here:
        btnParametroConfig.setBackground(new Color(241, 234, 204));
    }//GEN-LAST:event_btnParametroConfigMouseEntered

    private void btnOCompraConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOCompraConfigMouseExited
        // TODO add your handling code here:
        btnOCompraConfig.setBackground(new Color(235,224,179));
    }//GEN-LAST:event_btnOCompraConfigMouseExited

    private void btnOCompraConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOCompraConfigMouseEntered
        // TODO add your handling code here:
        btnOCompraConfig.setBackground(new Color(241, 234, 204));
    }//GEN-LAST:event_btnOCompraConfigMouseEntered

    private void btnDProdConfig1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDProdConfig1MouseExited
        // TODO add your handling code here:
        btnDProdConfig1.setBackground(new Color(235,224,179));
    }//GEN-LAST:event_btnDProdConfig1MouseExited

    private void btnDProdConfig1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDProdConfig1MouseEntered
        // TODO add your handling code here:
        btnDProdConfig1.setBackground(new Color(241, 234, 204));
    }//GEN-LAST:event_btnDProdConfig1MouseEntered
    void setColor(JPanel panel){
        panel.setBackground(new Color(241, 234, 204));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(235, 224, 179));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnDProdConfig;
    private javax.swing.JPanel btnDProdConfig1;
    private javax.swing.JPanel btnOCompraConfig;
    private javax.swing.JPanel btnParametroConfig;
    private javax.swing.JPanel btnUserConfig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    // End of variables declaration//GEN-END:variables
}
