/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BussinessObject.DetalleProductoBO;
import BussinessObject.ProductoBO;
import DataTransferObject.ProductoDTO;
import Implementacion.IDaoGeneral;
import static Presentacion.DashBoard.content;
import Type.BaseDatos;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FrmDProd1 extends javax.swing.JPanel {

   BaseDatos Gestor;
    IDaoGeneral ProductoDao;
    ProductoBO Bo;
    DetalleProductoBO Detalle;
      DefaultTableModel dtm = new DefaultTableModel();
    public FrmDProd1() {
                 ProductoDao = FrmLogin.dao;
        Gestor =FrmLogin.base;
        Bo = new ProductoBO(ProductoDao.ProductoClass(Gestor));
        Detalle = new DetalleProductoBO(ProductoDao.DetalleProductoClass(Gestor));
        initComponents();
        txtCodigoPedido.setText(FrmPedido1.CodVenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducto2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtPrecioU = new javax.swing.JTextField();
        txtCodProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoPedido = new javax.swing.JTextField();
        txtImporteTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(199, 192, 165));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/115695_magnifying glass_zoom_find_search_icon.png"))); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.setAlignmentY(0.0F);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, 30));

        buscar.setForeground(new java.awt.Color(102, 102, 102));
        buscar.setText("Search...");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarMousePressed(evt);
            }
        });
        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 450, 30));

        tbProducto2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Stock", "PrecioV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProducto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbProducto2MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbProducto2);
        if (tbProducto2.getColumnModel().getColumnCount() > 0) {
            tbProducto2.getColumnModel().getColumn(1).setPreferredWidth(480);
            tbProducto2.getColumnModel().getColumn(2).setPreferredWidth(40);
            tbProducto2.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 580, 370));

        jPanel1.setBackground(new java.awt.Color(129, 94, 75));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "DATOS DEL PEDIDO\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtPrecioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 106, -1));
        jPanel1.add(txtCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 75, 110, -1));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 106, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CÓDIGO DE PEDIDO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 38, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CÓDIGO DE PRODUCTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 78, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 130, 260, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CANTIDAD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("IMPORTE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(txtCodigoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 132, -1));

        txtImporteTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtImporteTotalKeyPressed(evt);
            }
        });
        jPanel1.add(txtImporteTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 106, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRECIO UNITARIO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jButton2.setBackground(new java.awt.Color(214, 238, 181));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/32379_add_plus_icon.png"))); // NOI18N
        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 231, 130, 40));

        jButton3.setBackground(new java.awt.Color(248, 176, 191));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9004715_cross_delete_remove_cancel_icon (1).png"))); // NOI18N
        jButton3.setText("CANCELAR");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, 40));

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 300, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo DeP.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             this.limpiarTabla();
       this.Listar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMousePressed
        // TODO add your handling code here:
        if (String.valueOf(buscar.getText()).equals("Search...")) {
            buscar.setText("");
            buscar.setForeground(Color.black);
        }
    }//GEN-LAST:event_buscarMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String x = this.Agregar();
            JOptionPane.showMessageDialog(null, x);       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         FrmPedido1 p1 = new FrmPedido1();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbProducto2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProducto2MousePressed
            int fila = tbProducto2.getSelectedRow();
      if(fila ==-1){
          JOptionPane.showMessageDialog(null, "seleccionar correctamente");
      }else{
         txtCodProducto.setText(tbProducto2.getValueAt(fila, 0).toString());
         txtNombre.setText(tbProducto2.getValueAt(fila, 1).toString());
      }
      txtCantidad.setText("");
      txtImporteTotal.setText("");
      txtPrecioU.setText("");
      
    }//GEN-LAST:event_tbProducto2MousePressed

    private void txtImporteTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteTotalKeyPressed
        try {
            int cantidad = Integer.parseInt(txtCantidad.getText());
            float PrecioU = Float.parseFloat(txtPrecioU.getText());
            float res = cantidad*PrecioU;
            txtImporteTotal.setText(String.valueOf(res));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "los datos deben ser numericos", "Error en el sistema", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtImporteTotalKeyPressed
  private void limpiarTabla() {
        dtm = (DefaultTableModel) tbProducto2.getModel();
        dtm.getDataVector().removeAllElements();
        tbProducto2.removeAll();
    }
      private void Listar() {  //venta
        dtm = (DefaultTableModel) tbProducto2.getModel();
        Object[] obj = new Object[4];
        for (ProductoDTO a : Bo.listarProductoVenta()) {
            obj[0] = a.getIdProducto().trim();
            obj[1] = a.getNombre().trim();
            obj[2] = a.getStock();     
            obj[3] = a.getPrecioV();
            dtm.addRow(obj);
        }
    }
  public String Agregar(){
        String Estado = Detalle.Agregar(txtCodigoPedido.getText(), txtCodProducto.getText(),Integer.parseInt( txtCantidad.getText()), Float.parseFloat(txtPrecioU.getText()),Float.parseFloat(txtImporteTotal.getText().trim()));
        return Estado;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProducto2;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtCodigoPedido;
    private javax.swing.JTextField txtImporteTotal;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioU;
    // End of variables declaration//GEN-END:variables
}
