/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BussinessObject.ClienteBO;
import BussinessObject.DetalleVentaBO;
import BussinessObject.UsuarioBO;
import BussinessObject.VentaBO;
import DataTransferObject.ClienteDTO;
import DataTransferObject.DetalleVentaDTO;
import DataTransferObject.UsuarioDTO;
import Implementacion.IDaoGeneral;
import static Presentacion.DashBoard.content;
import Reportes.Boleta;
import Type.BaseDatos;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FrmNuevaVenta extends javax.swing.JPanel {

    BaseDatos Gestor;
     IDaoGeneral ClienteDao;
     ClienteBO Bo;
     VentaBO ventaBo;
     UsuarioBO UsuarioBo;
     DetalleVentaBO VentaDBO;
       DefaultTableModel dtm2 = new DefaultTableModel();
       float suma=0;
    public FrmNuevaVenta() {
        initComponents();
        ClienteDao = FrmLogin.dao;
        Gestor = FrmLogin.base;
        Bo = new ClienteBO(ClienteDao.ClienteClass(Gestor));
        ventaBo = new VentaBO(ClienteDao.VentaClass(Gestor));
        UsuarioBo = new UsuarioBO(ClienteDao.UsuarioClass(Gestor));
        VentaDBO = new DetalleVentaBO(ClienteDao.DetalleVentaClass(Gestor));
        txtCodigoCliente.setText(FrmVistaCliente1.IdCliente2);
        txtCodigoEmpleado.setText(FrmVistaUser1.IdUsuario2);
         txtCodVenta.setText(CodVenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducto = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        btnNuevoCl2 = new javax.swing.JButton();
        btnGuardarCl2 = new javax.swing.JButton();
        btnCancelarCl2 = new javax.swing.JButton();
        btnEliminarCl2 = new javax.swing.JButton();
        btnSalirCl2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        txtDireccion = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAddCli = new javax.swing.JButton();
        txtNombre1 = new javax.swing.JTextField();
        txtCodVenta = new javax.swing.JTextField();
        pago = new javax.swing.JTextField();
        btnAddPro = new javax.swing.JButton();
        btnDeletePro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMontoTotal = new javax.swing.JTextField();
        cbxTipo = new javax.swing.JComboBox<>();
        jcbIGV = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtVuelto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtDNI1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtCodigoEmpleado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnAddCli1 = new javax.swing.JButton();
        txtNombre2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1080, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 51, 0)));
        tbProducto.setFont(new java.awt.Font("Lucida Bright", 0, 10)); // NOI18N
        tbProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Descuento", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbProducto);
        if (tbProducto.getColumnModel().getColumnCount() > 0) {
            tbProducto.getColumnModel().getColumn(1).setPreferredWidth(500);
            tbProducto.getColumnModel().getColumn(2).setPreferredWidth(60);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 640, 130));

        jPanel13.setBackground(new java.awt.Color(167, 144, 131));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoCl2.setBackground(new java.awt.Color(199, 192, 165));
        btnNuevoCl2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnNuevoCl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9004815_add_file_document_page_icon.png"))); // NOI18N
        btnNuevoCl2.setText("NUEVO");
        jPanel13.add(btnNuevoCl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, 113, -1));

        btnGuardarCl2.setBackground(new java.awt.Color(199, 192, 165));
        btnGuardarCl2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnGuardarCl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/285657_floppy_guardar_save_icon (1).png"))); // NOI18N
        btnGuardarCl2.setText("GUARDAR");
        btnGuardarCl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCl2ActionPerformed(evt);
            }
        });
        jPanel13.add(btnGuardarCl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 64, -1, -1));

        btnCancelarCl2.setBackground(new java.awt.Color(199, 192, 165));
        btnCancelarCl2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnCancelarCl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9004715_cross_delete_remove_cancel_icon (1).png"))); // NOI18N
        btnCancelarCl2.setText("CANCELAR");
        jPanel13.add(btnCancelarCl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 18, -1, -1));

        btnEliminarCl2.setBackground(new java.awt.Color(199, 192, 165));
        btnEliminarCl2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnEliminarCl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/39263_print_printer_icon (1).png"))); // NOI18N
        btnEliminarCl2.setText("IMPRIMIR");
        btnEliminarCl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCl2ActionPerformed(evt);
            }
        });
        jPanel13.add(btnEliminarCl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 64, -1, -1));

        btnSalirCl2.setBackground(new java.awt.Color(199, 192, 165));
        btnSalirCl2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnSalirCl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/3005766_account_door_exit_logout_icon.png"))); // NOI18N
        btnSalirCl2.setText("SALIR");
        jPanel13.add(btnSalirCl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 60));

        add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 420, 110));

        jPanel1.setBackground(new java.awt.Color(129, 94, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FECHA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CÓDIGO DE VENTA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jdcFecha.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 120, -1));

        jPanel3.setBackground(new java.awt.Color(129, 94, 75));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "DATOS DEL CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, -1));

        txtDNI.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel3.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 120, -1));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 190, -1));

        txtCodigoCliente.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCodigoCliente.setText("Clik aqui");
        txtCodigoCliente.setEnabled(false);
        txtCodigoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoClienteMousePressed(evt);
            }
        });
        txtCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoClienteActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOMBRE");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("APELLIDOS");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DIRECCIÓN");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CÓDIGO");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        btnAddCli.setBackground(new java.awt.Color(199, 192, 165));
        btnAddCli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/49576_new_add_plus_user_icon (1).png"))); // NOI18N
        btnAddCli.setText("CLIENTE");
        btnAddCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCliActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 50));

        txtNombre1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel3.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 600, 130));

        txtCodVenta.setEditable(false);
        txtCodVenta.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCodVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodVentaMousePressed(evt);
            }
        });
        jPanel1.add(txtCodVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 640, 200));

        pago.setForeground(new java.awt.Color(102, 102, 102));
        pago.setText("INGRESE EL PAGO");
        pago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pagoFocusGained(evt);
            }
        });
        pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pagoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pagoMousePressed(evt);
            }
        });
        pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoActionPerformed(evt);
            }
        });
        add(pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 130, 30));

        btnAddPro.setBackground(new java.awt.Color(214, 238, 181));
        btnAddPro.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnAddPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/32379_add_plus_icon.png"))); // NOI18N
        btnAddPro.setText("AGREGAR PRODUCTO(S)");
        btnAddPro.setAlignmentY(0.0F);
        btnAddPro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProActionPerformed(evt);
            }
        });
        add(btnAddPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 180, -1));

        btnDeletePro.setBackground(new java.awt.Color(238, 186, 178));
        btnDeletePro.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnDeletePro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/7697_fewer_icon.png"))); // NOI18N
        btnDeletePro.setText("MOSTRAR PRODUCTO(S)");
        btnDeletePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProActionPerformed(evt);
            }
        });
        add(btnDeletePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setText("LISTADO DE PRODUCTOS A VENDER");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 20));

        txtMontoTotal.setEditable(false);
        txtMontoTotal.setText("0.00");
        add(txtMontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 90, 30));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "BOLETA", "FACTURA" }));
        add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 140, 30));

        jcbIGV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbIGV.setForeground(new java.awt.Color(255, 255, 255));
        jcbIGV.setText("IGV");
        jcbIGV.setOpaque(false);
        jcbIGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbIGVActionPerformed(evt);
            }
        });
        add(jcbIGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PAGO");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TIPO DE COMPROBANTE");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MONTO TOTAL");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("VUELTO");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        txtVuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVueltoActionPerformed(evt);
            }
        });
        add(txtVuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 90, 30));

        jPanel4.setBackground(new java.awt.Color(129, 94, 75));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "DATOS DEL VENDEDOR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDNI1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel4.add(txtDNI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, -1));

        txtApellido1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel4.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, -1));

        txtCodigoEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCodigoEmpleado.setText("Clik Aqui");
        txtCodigoEmpleado.setEnabled(false);
        txtCodigoEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoEmpleadoMousePressed(evt);
            }
        });
        txtCodigoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEmpleadoActionPerformed(evt);
            }
        });
        jPanel4.add(txtCodigoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 90, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DNI");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NOMBRE");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("APELLIDOS");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CÓDIGO");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnAddCli1.setBackground(new java.awt.Color(199, 192, 165));
        btnAddCli1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddCli1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/41743_mypc_add_icon.png"))); // NOI18N
        btnAddCli1.setText("EMPLEADO");
        btnAddCli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCli1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddCli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 50));

        txtNombre2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 115, 270, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo det venta.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoActionPerformed
     float vuelto;
        try {
            vuelto = Float.parseFloat(pago.getText());
            vuelto-=suma;
            txtVuelto.setText(String.valueOf(vuelto));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Dato ingresado no es numerico");         
        }
    }//GEN-LAST:event_pagoActionPerformed

    private void txtVueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVueltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVueltoActionPerformed

    private void txtCodigoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEmpleadoActionPerformed

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActionPerformed

    private void btnAddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProActionPerformed
        // TODO add your handling code here:
       try {
            this.Agregar();
        } catch (Exception e) {
            System.out.println("no se puede agregar la venta :(");
        }
        
        
        FrmVistaProd p1 = new FrmVistaProd();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
       // content.repaint();
    }//GEN-LAST:event_btnAddProActionPerformed

    private void btnAddCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCliActionPerformed
        ClienteDTO obj = Bo.VentaCliente(txtCodigoCliente.getText());
        if(obj!=null){
            txtNombre1.setText(obj.getIdCliente().trim());
            txtApellido.setText(obj.getIdPersona().trim());
            txtDireccion.setText(obj.getObservaciones().trim());
            txtDNI.setText(obj.getEstado().trim());
            System.out.println("no esta vacio");
        }else{
            System.out.println("esta vacio :( ");
        }
    }//GEN-LAST:event_btnAddCliActionPerformed

    private void btnAddCli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCli1ActionPerformed
           UsuarioDTO obj = UsuarioBo.BuscarVenta(txtCodigoEmpleado.getText());
        if(obj!=null){
            txtNombre2.setText(obj.getIdUsuario().trim());
            txtApellido1.setText(obj.getIdPersona().trim());
           // txtDireccion1.setText(obj.getNivel().trim());
            txtDNI1.setText(obj.getEstadoTxt().trim());
            System.out.println("no esta vacio");
        }else{
            System.out.println("esta vacio :( ");
        }
    }//GEN-LAST:event_btnAddCli1ActionPerformed

    private void pagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(pago.getText()).equals("INGRESE EL PAGO")) {
            pago.setText("");
            pago.setForeground(Color.black);
        }
    }//GEN-LAST:event_pagoMousePressed

    private void txtCodigoClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoClienteMousePressed
               FrmVistaCliente1 p1 = new FrmVistaCliente1();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_txtCodigoClienteMousePressed

    private void txtCodigoEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoEmpleadoMousePressed
         // TODO add your handling code here:
        FrmVistaUser1 p1 = new FrmVistaUser1();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_txtCodigoEmpleadoMousePressed

    private void txtCodVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodVentaMousePressed
        CodVenta = ventaBo.CodigoVenta();
        txtCodVenta.setText(CodVenta);
    }//GEN-LAST:event_txtCodVentaMousePressed

    private void btnDeleteProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProActionPerformed
      this.limpiarTabla();
      this.Listar();
      txtMontoTotal.setText("S/"+String.valueOf(suma));
    }//GEN-LAST:event_btnDeleteProActionPerformed

    private void pagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagoMouseEntered

    }//GEN-LAST:event_pagoMouseEntered

    private void btnGuardarCl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCl2ActionPerformed
        try {
            this.Actualizar();
            JOptionPane.showMessageDialog(null, "La venta se a realizado con exito", "Mensaje de confirmacion", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "A ocurrido un error", "Mensaje de Error"+e, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarCl2ActionPerformed

    private void jcbIGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbIGVActionPerformed

    }//GEN-LAST:event_jcbIGVActionPerformed

    private void btnEliminarCl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCl2ActionPerformed
        try {
            Boleta.BoletaElectronica(txtNombre1.getText(), Bo,txtCodigoCliente.getText(),
                    UsuarioBo,txtCodigoEmpleado.getText(),VentaDBO,txtCodVenta.getText(),suma);
            JOptionPane.showMessageDialog(null, "La boleta electronica se creo satisfactoriamente", "Mensaje de confirmacion", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_btnEliminarCl2ActionPerformed

    private void pagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pagoFocusGained

        System.out.println("hola 3");
    }//GEN-LAST:event_pagoFocusGained
    private void Agregar()throws Exception{
        String Mensaje = ventaBo.Agregar(txtCodVenta.getText().trim(), txtCodigoEmpleado.getText(),
                txtCodigoCliente.getText(),jdcFecha.getDate(), "Boleta", 0.00f, 0.00f,"Activo");
        System.out.println(Mensaje);
        System.out.println(jdcFecha.getDate());
    }
    private void Actualizar()throws Exception{
       String Mensaje="";
        if(jcbIGV.isSelected()){
            suma = suma - suma*0.18f;
            txtMontoTotal.setText("S/ "+String.valueOf(suma));
           Mensaje = ventaBo.Actualizar(txtCodVenta.getText(), txtCodigoEmpleado.getText(), txtCodigoCliente.getText(), jdcFecha.getDate(), cbxTipo.getSelectedItem().toString(), suma, 0.18f, "Activo");
        }else{
            Mensaje = ventaBo.Actualizar(txtCodVenta.getText(), txtCodigoEmpleado.getText(), txtCodigoCliente.getText(), jdcFecha.getDate(), cbxTipo.getSelectedItem().toString(), suma, 0.00f, "Activo");
        }
    }
     private void limpiarTabla() {
        dtm2 = (DefaultTableModel) tbProducto.getModel();
        dtm2.getDataVector().removeAllElements();
        tbProducto.removeAll();
    }
      private void Listar() {  //venta
        dtm2 = (DefaultTableModel) tbProducto.getModel();
        Object[] obj = new Object[5];
        for (DetalleVentaDTO a : VentaDBO.listar(txtCodVenta.getText())) {
            obj[0] = a.getIdVenta().trim();
            obj[1] = a.getIdProducto().trim();
            obj[2] = a.getCantidad();     
            obj[4] = a.getDescuento();
            suma += a.getDescuento();
            obj[3] = a.getPrecioUnitario();
            dtm2.addRow(obj);
        }
    }
    public static String CodVenta;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCli;
    private javax.swing.JButton btnAddCli1;
    private javax.swing.JButton btnAddPro;
    private javax.swing.JButton btnCancelarCl2;
    private javax.swing.JButton btnDeletePro;
    private javax.swing.JButton btnEliminarCl2;
    private javax.swing.JButton btnGuardarCl2;
    private javax.swing.JButton btnNuevoCl2;
    private javax.swing.JButton btnSalirCl2;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbIGV;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTextField pago;
    private javax.swing.JTable tbProducto;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtCodVenta;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoEmpleado;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDNI1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtVuelto;
    // End of variables declaration//GEN-END:variables
}
