/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BussinessObject.ParametroBO;
import DataTransferObject.ParametroDTO;
import Implementacion.IDaoGeneral;
import static Presentacion.DashBoard.content;
import Type.BaseDatos;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FrmParametro extends javax.swing.JPanel {

    BaseDatos Gestor;
    IDaoGeneral ParametroDao;
    ParametroBO Bo;
    DefaultTableModel dtm = new DefaultTableModel();
    
    
    public static String IdParametro;
    public FrmParametro() {
        initComponents();
       ParametroDao = FrmLogin.dao;
        Gestor =FrmLogin.base;
        Bo = new ParametroBO(ParametroDao.ParametroClass(Gestor));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JCheckBox();
        txtDescripcion = new javax.swing.JTextField();
        cbxTipo = new javax.swing.JComboBox<>();
        txtIdParametro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbParametro = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        btnNuevoCl = new javax.swing.JButton();
        btnGuardarCl = new javax.swing.JButton();
        btnCancelarCl = new javax.swing.JButton();
        btnModificarCl = new javax.swing.JButton();
        btnEliminarCl = new javax.swing.JButton();
        btnSalirCl = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnMarca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ESTADO");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DESCRIPCIÓN");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TIPO");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID PARÁMETRO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jcbEstado.setText("ACTIVO");
        add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, -1, 30));

        txtDescripcion.setForeground(new java.awt.Color(102, 102, 102));
        txtDescripcion.setText("INGRESE LA DESCRIPCIÓN");
        txtDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDescripcionMousePressed(evt);
            }
        });
        add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 360, -1));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nivel", "CATEGORIA", "Documento", "MARCA" }));
        add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        txtIdParametro.setForeground(new java.awt.Color(102, 102, 102));
        txtIdParametro.setText("Click IdParametro");
        txtIdParametro.setEnabled(false);
        txtIdParametro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdParametroMousePressed(evt);
            }
        });
        add(txtIdParametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 240, -1));

        tbParametro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Parámetro", "Descripción", "Tipo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbParametro.setGridColor(new java.awt.Color(255, 255, 255));
        tbParametro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbParametroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbParametroMousePressed(evt);
            }
        });
        tbParametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbParametroKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbParametro);
        if (tbParametro.getColumnModel().getColumnCount() > 0) {
            tbParametro.getColumnModel().getColumn(0).setPreferredWidth(200);
            tbParametro.getColumnModel().getColumn(1).setPreferredWidth(480);
            tbParametro.getColumnModel().getColumn(2).setPreferredWidth(300);
            tbParametro.getColumnModel().getColumn(3).setPreferredWidth(130);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 630, 350));

        jPanel11.setBackground(new java.awt.Color(167, 144, 131));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnNuevoCl.setBackground(new java.awt.Color(163, 149, 126));
        btnNuevoCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/49576_new_add_plus_user_icon.png"))); // NOI18N
        btnNuevoCl.setText("Listar datos");
        btnNuevoCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClActionPerformed(evt);
            }
        });

        btnGuardarCl.setBackground(new java.awt.Color(163, 149, 126));
        btnGuardarCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/285657_floppy_guardar_save_icon.png"))); // NOI18N
        btnGuardarCl.setText("GUARDAR");
        btnGuardarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClActionPerformed(evt);
            }
        });

        btnCancelarCl.setBackground(new java.awt.Color(163, 149, 126));
        btnCancelarCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9004715_cross_delete_remove_cancel_icon.png"))); // NOI18N
        btnCancelarCl.setText("CANCELAR");

        btnModificarCl.setBackground(new java.awt.Color(163, 149, 126));
        btnModificarCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/8726304_refresh_icon.png"))); // NOI18N
        btnModificarCl.setText("MODIFICAR");
        btnModificarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClActionPerformed(evt);
            }
        });

        btnEliminarCl.setBackground(new java.awt.Color(163, 149, 126));
        btnEliminarCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/352303_delete_icon.png"))); // NOI18N
        btnEliminarCl.setText("ELIMINAR");
        btnEliminarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClActionPerformed(evt);
            }
        });

        btnSalirCl.setBackground(new java.awt.Color(163, 149, 126));
        btnSalirCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/8725805_exit_icon.png"))); // NOI18N
        btnSalirCl.setText("SALIR");

        btnCategoria.setText("CATEGORIA");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnMarca.setText("MARCA");
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnNuevoCl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnGuardarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarCl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCategoria, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalirCl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(btnMarca)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCategoria)
                    .addComponent(btnMarca))
                .addGap(40, 40, 40))
        );

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 260, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoParametro.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdParametroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdParametroMousePressed
        txtIdParametro.setText(this.Codigo());      
        txtDescripcion.setText("");
        jcbEstado.setSelected(false);
    }//GEN-LAST:event_txtIdParametroMousePressed

    private void txtDescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDescripcionMousePressed
        // TODO add your handling code here:   
    }//GEN-LAST:event_txtDescripcionMousePressed

    private void btnGuardarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClActionPerformed
        try {
           String x = this.Agregar();
           JOptionPane.showMessageDialog(null,x, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGuardarClActionPerformed

    private void btnNuevoClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClActionPerformed
         this.limpiarTabla();
        this.Listar();
    }//GEN-LAST:event_btnNuevoClActionPerformed

    private void btnModificarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClActionPerformed
        String x;
        try {
            x = this.Actualizar();
            JOptionPane.showMessageDialog(null, x, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificarClActionPerformed

    private void btnEliminarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClActionPerformed
        try {
            String x = this.Eliminar();
            JOptionPane.showMessageDialog(null, x, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEliminarClActionPerformed

    private void tbParametroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbParametroMousePressed
      int fila = tbParametro.getSelectedRow();
      if(fila ==-1){
          JOptionPane.showMessageDialog(null, "seleccionar correctamente");
      }else{
          txtIdParametro.setText(tbParametro.getValueAt(fila, 0).toString());
          cbxTipo.setSelectedItem(tbParametro.getValueAt(fila, 1).toString().trim());
          txtDescripcion.setText(tbParametro.getValueAt(fila, 2).toString());
          jcbEstado.setSelected(tbParametro.getValueAt(fila, 3).equals("Activo"));
      }
      
    }//GEN-LAST:event_tbParametroMousePressed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
               this.limpiarTabla();
               this.Marca();
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
                this.limpiarTabla();
                this.Categoria();
                
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void tbParametroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbParametroMouseExited
      
    }//GEN-LAST:event_tbParametroMouseExited

    private void tbParametroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbParametroKeyPressed
       /**
        *       int fila = tbCliente.getSelectedRow();
      int x =  JOptionPane.showConfirmDialog(null, "Desea actualizar la informacion?", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
      if(x==0){
          IdCliente = tbCliente.getValueAt(fila, 0).toString();
          IdPersona =tbCliente.getValueAt(fila, 1).toString();
          TipoD = tbCliente.getValueAt(fila, 3).toString();
         this.hola();
      }else{
          System.out.println("hola por aqui");
      }
        */
       String estado;
       int fila = tbParametro.getSelectedRow();
       IdParametro = tbParametro.getValueAt(fila,0).toString();
       estado = tbParametro.getValueAt(fila, 3).toString();
       String Descripcion = tbParametro.getValueAt(fila, 1).toString();
       if(estado.equals("Activo")){
           if (Descripcion.equals("CATEGORIA")) {
               FrmProducto1 p1 = new FrmProducto1();
               p1.setSize(1070, 630);
               p1.setLocation(0, 0);

               content.removeAll();
               content.add(p1, BorderLayout.CENTER);
               content.revalidate();
               content.repaint();
           }else{
               FrmPedido1 p1 = new FrmPedido1();
               p1.setSize(1070, 630);
               p1.setLocation(0, 0);

               content.removeAll();
               content.add(p1, BorderLayout.CENTER);
               content.revalidate();
               content.repaint();
           }
       }else{
           JOptionPane.showMessageDialog(null, "El parametro esta inactivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
       }
       
       
    }//GEN-LAST:event_tbParametroKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCl;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnEliminarCl;
    private javax.swing.JButton btnGuardarCl;
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnModificarCl;
    private javax.swing.JButton btnNuevoCl;
    private javax.swing.JButton btnSalirCl;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbEstado;
    private javax.swing.JTable tbParametro;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdParametro;
    // End of variables declaration//GEN-END:variables
    private String Agregar()throws Exception{
        String Mensaje;
      txtIdParametro.setText(this.Codigo());
        Mensaje = Bo.Agregar(txtIdParametro.getText(),cbxTipo.getSelectedItem().toString(), txtDescripcion.getText(),this.Estado(jcbEstado.isSelected()));
        return Mensaje;
    }
    private String Estado(boolean obj){
        if(obj){
            return "Activo";
        }
        return "Inactivo";
    }
    private void Listar() {  //venta
        dtm = (DefaultTableModel) tbParametro.getModel();
        Object[] obj = new Object[4];
        for (ParametroDTO a : Bo.listar()) {
            obj[0] = a.getIdParamero().trim();
            obj[1] = a.getDescripcion().trim();
            obj[2] = a.getTipo().trim();
            obj[3] = a.getEstadoText().trim();
            dtm.addRow(obj);
        }
    }
     private void Categoria() {  //venta
        dtm = (DefaultTableModel) tbParametro.getModel();
        Object[] obj = new Object[4];
        for (ParametroDTO a : Bo.listarCategoria()) {
            obj[0] = a.getIdParamero().trim();
            obj[1] = a.getDescripcion().trim();
            obj[2] = a.getTipo().trim();
            obj[3] = a.getEstadoText().trim();
            dtm.addRow(obj);
        }
    }
      private void Marca() {  //venta
        dtm = (DefaultTableModel) tbParametro.getModel();
        Object[] obj = new Object[4];
        for (ParametroDTO a : Bo.listarMarca()) {
            obj[0] = a.getIdParamero().trim();
            obj[1] = a.getDescripcion().trim();
            obj[2] = a.getTipo().trim();
            obj[3] = a.getEstadoText().trim();
            dtm.addRow(obj);
        }
    }

    private String Codigo() {
        return Bo.CodigoParametro();
    }
    private void limpiarTabla() {
        dtm = (DefaultTableModel) tbParametro.getModel();
        dtm.getDataVector().removeAllElements();
        tbParametro.removeAll();
    }
    private String Actualizar()throws Exception{
        String Mensaje;
        Mensaje = Bo.Actualizar(txtIdParametro.getText().trim(),cbxTipo.getSelectedItem().toString(), txtDescripcion.getText().trim(),this.Estado(jcbEstado.isSelected()));
        return Mensaje;
    }
    private String Eliminar()throws Exception{
        String Mensaje;
        Mensaje= Bo.Eliminar(txtIdParametro.getText().trim());
        return Mensaje;
    }
    
}
