/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import java.time.LocalDate;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author LENOVO
 */
public class FrmPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        
        
        LocalDate now = LocalDate.now(); 
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," ;Septiembre"
            ,"Octubre","Noviembre","Diciembre"};
        fecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
        
        
        Calendar calendario= new GregorianCalendar();
        int hora= calendario.get(Calendar.HOUR_OF_DAY);
        
       if(hora>=6 || hora<12){
        textHora.setText("Buenos días");
       }
       if(hora>=12 || hora<=18){
        textHora.setText("Buenas tardes");
       }
      if(hora>=19){
        textHora.setText("Buenas noches");
       }
      
      
    
    }
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        textHora = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 224, 179));
        setPreferredSize(new java.awt.Dimension(1080, 630));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(160, 113, 83));
        jLabel1.setText("Bienvenido");
        add(jLabel1);
        jLabel1.setBounds(52, 237, 337, 47);

        Header.setBackground(new java.awt.Color(241, 234, 204));

        fecha.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        fecha.setForeground(new java.awt.Color(135, 121, 86));
        fecha.setText("Hoy es Sábado 28 de Octubre de 2022,");

        textHora.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 28)); // NOI18N
        textHora.setForeground(new java.awt.Color(135, 121, 86));
        textHora.setText("¡BUENOS ...!");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha)
                    .addComponent(textHora, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(680, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(textHora, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        add(Header);
        Header.setBounds(0, 46, 1080, 146);

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Sistema de Ventas para la empresa \"INVERSIONES D y E\". Controle, administre y realice");
        add(Text1);
        Text1.setBounds(52, 315, 531, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("las distintas funciones (registrar una venta, producto, proveedor y cliente) de forma óptima y de fácil interacción. ");
        add(jLabel3);
        jLabel3.setBounds(52, 335, 688, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Este sistema le permitirá llevar un control y registro adecuado de las ventas de la mueblería");
        add(jLabel4);
        jLabel4.setBounds(52, 368, 556, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("y, así mismo tendrá acceso a distintas herramientas para tareas específicas, como lo son:");
        add(jLabel5);
        jLabel5.setBounds(52, 388, 537, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("• Ejecutar una venta");
        add(jLabel6);
        jLabel6.setBounds(52, 445, 170, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("• Controlar las ventas");
        add(jLabel7);
        jLabel7.setBounds(52, 465, 170, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("• Registro de Proveedores, Clientes, Productos y Ventas");
        add(jLabel8);
        jLabel8.setBounds(52, 485, 389, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("• Actualización Proveedores, Clientes, Productos y Ventas");
        add(jLabel9);
        jLabel9.setBounds(52, 505, 351, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("• Eliminar todo tipo de Registros");
        add(jLabel10);
        jLabel10.setBounds(52, 525, 330, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("• Sección de Reportes, donde puede generar documentos");
        add(jLabel11);
        jLabel11.setBounds(52, 545, 351, 20);

        slogan.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        slogan.setForeground(new java.awt.Color(106, 75, 55));
        slogan.setText("We create memories in every space of your house!");
        add(slogan);
        slogan.setBounds(20, 13, 370, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mueble4 (1).png"))); // NOI18N
        add(jLabel12);
        jLabel12.setBounds(580, 370, 300, 210);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel textHora;
    // End of variables declaration//GEN-END:variables


}
