/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;


import BussinessObject.PersonaBO;
import BussinessObject.ProveedorBO;
import Implementacion.IDaoGeneral;
import static Presentacion.DashBoard.content;
import Type.BaseDatos;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;


public class FrmProveedor extends javax.swing.JPanel {

    BaseDatos Gestor;
     IDaoGeneral ClienteDao;
     ProveedorBO Bo;
     PersonaBO Bo2;
    public FrmProveedor() {
        initComponents();
                ClienteDao = FrmLogin.dao;
        Gestor = FrmLogin.base;
        Bo = new ProveedorBO(ClienteDao.ProveedorClass(Gestor));
        Bo2 = new PersonaBO(ClienteDao.PersonaClass(Gestor));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        btnNuevoCl1 = new javax.swing.JButton();
        btnGuardarCl1 = new javax.swing.JButton();
        btnCancelarCl1 = new javax.swing.JButton();
        btnModificarCl1 = new javax.swing.JButton();
        btnEliminarCl1 = new javax.swing.JButton();
        btnSalirCl1 = new javax.swing.JButton();
        Text4 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JTextField();
        text5 = new javax.swing.JLabel();
        text9 = new javax.swing.JLabel();
        text8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text10 = new javax.swing.JLabel();
        text11 = new javax.swing.JLabel();
        text12 = new javax.swing.JLabel();
        text13 = new javax.swing.JLabel();
        txtNumeroCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCodigoProv = new javax.swing.JTextField();
        txtCodigoPersona = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        cbxTipoDocumento = new javax.swing.JComboBox<>();
        txtNumeroDoc = new javax.swing.JTextField();
        txtReferencias = new javax.swing.JTextField();
        jcbEstado = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        rbtMasculino = new javax.swing.JRadioButton();
        rbtFemenino = new javax.swing.JRadioButton();
        FechaNac = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1070, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(167, 144, 131));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnNuevoCl1.setBackground(new java.awt.Color(163, 149, 126));
        btnNuevoCl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/49576_new_add_plus_user_icon.png"))); // NOI18N
        btnNuevoCl1.setText("LISTAR");
        btnNuevoCl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCl1ActionPerformed(evt);
            }
        });

        btnGuardarCl1.setBackground(new java.awt.Color(163, 149, 126));
        btnGuardarCl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/285657_floppy_guardar_save_icon.png"))); // NOI18N
        btnGuardarCl1.setText("GUARDAR");
        btnGuardarCl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCl1ActionPerformed(evt);
            }
        });

        btnCancelarCl1.setBackground(new java.awt.Color(163, 149, 126));
        btnCancelarCl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9004715_cross_delete_remove_cancel_icon.png"))); // NOI18N
        btnCancelarCl1.setText("CANCELAR");

        btnModificarCl1.setBackground(new java.awt.Color(163, 149, 126));
        btnModificarCl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/8726304_refresh_icon.png"))); // NOI18N
        btnModificarCl1.setText("MODIFICAR");
        btnModificarCl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCl1ActionPerformed(evt);
            }
        });

        btnEliminarCl1.setBackground(new java.awt.Color(163, 149, 126));
        btnEliminarCl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/352303_delete_icon.png"))); // NOI18N
        btnEliminarCl1.setText("ELIMINAR");

        btnSalirCl1.setBackground(new java.awt.Color(163, 149, 126));
        btnSalirCl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/8726304_refresh_icon.png"))); // NOI18N
        btnSalirCl1.setText("EXTRAER DATOS");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarCl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoCl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificarCl1)
                    .addComponent(btnCancelarCl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarCl1)
                    .addComponent(btnSalirCl1))
                .addGap(28, 28, 28))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 420, 140));

        Text4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text4.setForeground(new java.awt.Color(255, 255, 255));
        Text4.setText("REFERENCIAS");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        Text3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setText("NOMBRE");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("CÓDIGO");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FECHA DE NACIMIENTO");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("INGRESE EL NOMBRE");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 280, -1));

        txtObservaciones.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(102, 102, 102));
        txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
        txtObservaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtObservacionesMousePressed(evt);
            }
        });
        txtObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacionesActionPerformed(evt);
            }
        });
        add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 250, -1));

        text5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text5.setForeground(new java.awt.Color(255, 255, 255));
        text5.setText("TIPO DE DOCUMENTO");
        add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        text9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text9.setForeground(new java.awt.Color(255, 255, 255));
        text9.setText("NÚMERO DE DOC.");
        add(text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        text8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text8.setForeground(new java.awt.Color(255, 255, 255));
        text8.setText("ESTADO");
        add(text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("N° DE PERSONA");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        text10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text10.setForeground(new java.awt.Color(255, 255, 255));
        text10.setText("CELULAR");
        add(text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        text11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text11.setForeground(new java.awt.Color(255, 255, 255));
        text11.setText("CORREO");
        add(text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        text12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text12.setForeground(new java.awt.Color(255, 255, 255));
        text12.setText("DIRECCIÓN");
        add(text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

        text13.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text13.setForeground(new java.awt.Color(255, 255, 255));
        text13.setText("OBSERVACIONES");
        add(text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, -1, -1));

        txtNumeroCelular.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNumeroCelular.setForeground(new java.awt.Color(102, 102, 102));
        txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
        txtNumeroCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroCelularMousePressed(evt);
            }
        });
        txtNumeroCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCelularActionPerformed(evt);
            }
        });
        add(txtNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 280, -1));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreo.setText("INGRESE EL CORREO");
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 280, -1));

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion.setText("INGRESE LA DIRECCIÓN");
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionMousePressed(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 250, -1));

        txtCodigoProv.setEditable(false);
        txtCodigoProv.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCodigoProv.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoProv.setText("INGRESE EL CÓDIGO");
        txtCodigoProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoProvMousePressed(evt);
            }
        });
        txtCodigoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProvActionPerformed(evt);
            }
        });
        add(txtCodigoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 230, -1));

        txtCodigoPersona.setEditable(false);
        txtCodigoPersona.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCodigoPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoPersonaMousePressed(evt);
            }
        });
        add(txtCodigoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 140, -1));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setText("INGRESE LOS APELLIDOS");
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 280, -1));

        cbxTipoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DNI", "CARNET DE EXTRANJERÍA", "PASAPORTE" }));
        cbxTipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxTipoDocumentoMousePressed(evt);
            }
        });
        add(cbxTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 160, -1));

        txtNumeroDoc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNumeroDoc.setForeground(new java.awt.Color(102, 102, 102));
        txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
        txtNumeroDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroDocMousePressed(evt);
            }
        });
        add(txtNumeroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 160, -1));

        txtReferencias.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtReferencias.setForeground(new java.awt.Color(102, 102, 102));
        txtReferencias.setText("INGRESE LA REFERENCIA");
        txtReferencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtReferenciasMousePressed(evt);
            }
        });
        add(txtReferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 260, -1));

        jcbEstado.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(255, 255, 255));
        jcbEstado.setText("ACTIVO");
        add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jPanel2.setBackground(new java.awt.Color(167, 144, 131));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "SEXO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        rbtMasculino.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbtMasculino.setForeground(new java.awt.Color(102, 102, 102));
        rbtMasculino.setText("Masculino");

        rbtFemenino.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbtFemenino.setForeground(new java.awt.Color(102, 102, 102));
        rbtFemenino.setText("Femenino");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtMasculino)
                .addGap(18, 18, 18)
                .addComponent(rbtFemenino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMasculino)
                    .addComponent(rbtFemenino))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 190, 60));

        FechaNac.setDateFormatString("dd/MM/yyyy");
        add(FechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 160, -1));

        jSeparator1.setBackground(new java.awt.Color(235, 224, 179));
        jSeparator1.setForeground(new java.awt.Color(235, 224, 179));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 20, 230));

        jSeparator2.setBackground(new java.awt.Color(235, 224, 179));
        jSeparator2.setForeground(new java.awt.Color(235, 224, 179));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 20, 230));

        Text5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text5.setForeground(new java.awt.Color(255, 255, 255));
        Text5.setText("APELLIDOS");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedor.png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1075, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNombre.getText()).equals("INGRESE EL NOMBRE")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        if (txtCodigoProv.getText().isEmpty()) {
            txtCodigoProv.setText("INGRESE EL CÓDIGO");
            txtCodigoProv.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA REFERENCIA");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtObservacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtObservacionesMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtObservaciones.getText()).equals("INGRESE LA OBSERVACIÓN")) {
            txtObservaciones.setText("");
            txtObservaciones.setForeground(Color.black);
        }
        if (txtCodigoProv.getText().isEmpty()) {
            txtCodigoProv.setText("INGRESE EL CÓDIGO");
            txtCodigoProv.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA REFERENCIA");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtObservacionesMousePressed

    private void txtObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionesActionPerformed

    private void txtNumeroCelularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroCelularMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNumeroCelular.getText()).equals("INGRESE EL NÚMERO DE CEL.")) {
            txtNumeroCelular.setText("");
            txtNumeroCelular.setForeground(Color.black);
        }
        if (txtCodigoProv.getText().isEmpty()) {
            txtCodigoProv.setText("INGRESE EL CÓDIGO");
            txtCodigoProv.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA REFERENCIA");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNumeroCelularMousePressed

    private void txtNumeroCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCelularActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtCorreo.getText()).equals("INGRESE EL CORREO")) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
        if (txtCodigoProv.getText().isEmpty()) {
            txtCodigoProv.setText("INGRESE EL CÓDIGO");
            txtCodigoProv.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA REFERENCIA");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtDireccion.getText()).equals("INGRESE LA DIRECCIÓN")) {
            txtDireccion.setText("");
            txtDireccion.setForeground(Color.black);
        }
        if (txtCodigoProv.getText().isEmpty()) {
            txtCodigoProv.setText("INGRESE EL CÓDIGO");
            txtCodigoProv.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA REFERENCIA");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDireccionMousePressed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCodigoProvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProvMousePressed
         txtCodigoProv.setText(this.CodigoCliente(txtNumeroDoc.getText().substring(0, 6)));
        if (String.valueOf(txtCodigoProv.getText()).equals("INGRESE EL CÓDIGO")) {
            txtCodigoProv.setText("");
            txtCodigoProv.setForeground(Color.black);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE EL NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA REFERENCIA");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCodigoProvMousePressed

    private void txtCodigoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProvActionPerformed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtApellido.getText()).equals("INGRESE LOS APELLIDOS")) {
            txtApellido.setText("");
            txtApellido.setForeground(Color.black);
        }
        if (txtCodigoProv.getText().isEmpty()) {
            txtCodigoProv.setText("INGRESE EL CÓDIGO");
            txtCodigoProv.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA REFERENCIA");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtApellidoMousePressed

    private void cbxTipoDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxTipoDocumentoMousePressed
        // TODO add your handling code here:
        txtNumeroDoc.setVisible(true);
    }//GEN-LAST:event_cbxTipoDocumentoMousePressed

    private void txtNumeroDocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroDocMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNumeroDoc.getText()).equals("INGRESE NUMERO DE DOC.")) {
            txtNumeroDoc.setText("");
            txtNumeroDoc.setForeground(Color.black);
        }
        if (txtCodigoProv.getText().isEmpty()) {
            txtCodigoProv.setText("INGRESE EL CÓDIGO");
            txtCodigoProv.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA REFERENCIA");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNumeroDocMousePressed

    private void txtReferenciasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReferenciasMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNumeroDoc.getText()).equals("INGRESE LA REFERENCIA")) {
            txtNumeroDoc.setText("");
            txtNumeroDoc.setForeground(Color.black);
        }
        if (txtCodigoProv.getText().isEmpty()) {
            txtCodigoProv.setText("INGRESE EL CÓDIGO");
            txtCodigoProv.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroCelular.getText().isEmpty()) {
            txtNumeroCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtNumeroCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
        if (txtObservaciones.getText().isEmpty()) {
            txtObservaciones.setText("INGRESE LA OBSERVACIÓN");
            txtObservaciones.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtReferenciasMousePressed

    private void btnGuardarCl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCl1ActionPerformed
        // TODO add your handling code here:
      try {
            this.AgregarCliente();
            JOptionPane.showMessageDialog(null, "Proveedor agregado con exito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println("no funciona :(");
        }
    }//GEN-LAST:event_btnGuardarCl1ActionPerformed

    private void txtCodigoPersonaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoPersonaMousePressed
          txtCodigoPersona.setText(this.CodigoPersona());
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtNumeroCelular.setText("");
        txtNumeroDoc.setText("");
        txtObservaciones.setText("");
        cbxTipoDocumento.setSelectedIndex(0);
        FechaNac.setDate(null);
        rbtFemenino.setSelected(false);
        rbtMasculino.setSelected(false);
        jcbEstado.setSelected(true);
    }//GEN-LAST:event_txtCodigoPersonaMousePressed

    private void btnNuevoCl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCl1ActionPerformed
         FrmVistaProveedor p1 = new FrmVistaProveedor();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnNuevoCl1ActionPerformed

    private void btnModificarCl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarCl1ActionPerformed
private void AgregarCliente() throws Exception{
      String Mensaje1;
      String Mensaje2;
        System.out.println(txtCodigoPersona.getText());
       Mensaje2 = Bo2.Agregar(txtCodigoPersona.getText(), txtNombre.getText(), txtApellido.getText(), txtNumeroDoc.getText(), txtNumeroCelular.getText(), txtCorreo.getText(),
               this.Genero(rbtMasculino.isSelected()), FechaNac.getDate(), txtDireccion.getText(),this.ControlParametro(cbxTipoDocumento.getSelectedItem().toString()),this.Estado(jcbEstado.isSelected()));
        System.out.println(Mensaje2);
      Mensaje1 = Bo.Agregar(txtCodigoProv.getText(), txtCodigoPersona.getText(), txtObservaciones.getText(),txtReferencias.getText(),true);
        System.out.println(Mensaje1);
    }
  private String CodigoPersona(){
        return Bo2.CodigoPersona();
    }
    private String CodigoCliente(String x){
        String Tipo = cbxTipoDocumento.getSelectedItem().toString().substring(0, 3);
        return Tipo+"-"+Bo.CodigoCliente(x);
    }
     private String Estado(boolean o){
        if(o){
            return "Activo";
        }
        return "Inactivo";
    }
      private String Genero(boolean o){
        if(o){
            return "Masculino";
        }
        return "Femenino";
    }
    private String ControlParametro(String codigo) {
        if (codigo.equalsIgnoreCase("DNI")) {
            return "Parametro_01";
        } else {
            if (codigo.equalsIgnoreCase("CARNET DE EXTRANJERIA")) {
                return "Parametro_02";
            } else {
                    return "Parametro_03";
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaNac;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JButton btnCancelarCl1;
    private javax.swing.JButton btnEliminarCl1;
    private javax.swing.JButton btnGuardarCl1;
    private javax.swing.JButton btnModificarCl1;
    private javax.swing.JButton btnNuevoCl1;
    private javax.swing.JButton btnSalirCl1;
    private javax.swing.JComboBox<String> cbxTipoDocumento;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox jcbEstado;
    private javax.swing.JRadioButton rbtFemenino;
    private javax.swing.JRadioButton rbtMasculino;
    private javax.swing.JLabel text10;
    private javax.swing.JLabel text11;
    private javax.swing.JLabel text12;
    private javax.swing.JLabel text13;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel text9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigoPersona;
    private javax.swing.JTextField txtCodigoProv;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroCelular;
    private javax.swing.JTextField txtNumeroDoc;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtReferencias;
    // End of variables declaration//GEN-END:variables
}
