/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BussinessObject.DetalleProductoBO;
import BussinessObject.OrdenCompraBO;
import BussinessObject.ProveedorBO;
import BussinessObject.UsuarioBO;
import DataTransferObject.DetalleProductoDTO;
import DataTransferObject.ProveedorDTO;
import Implementacion.IDaoGeneral;
import static Presentacion.DashBoard.content;
import Type.BaseDatos;
import java.awt.BorderLayout;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FrmPedido1 extends javax.swing.JPanel {

     BaseDatos Gestor;
     IDaoGeneral ClienteDao;
     OrdenCompraBO Bo;
     ProveedorBO Bo2;
     DetalleProductoBO VentaDBO;
     DefaultTableModel dtm2 = new DefaultTableModel();
       float suma=0;
    public FrmPedido1() {
         ClienteDao = FrmLogin.dao;
        Gestor = FrmLogin.base;
       Bo = new OrdenCompraBO(ClienteDao.OrdenCompraClass(Gestor));
       Bo2 = new ProveedorBO(ClienteDao.ProveedorClass(Gestor));
       VentaDBO = new DetalleProductoBO(ClienteDao.DetalleProductoClass(Gestor));
        initComponents();
        txtMarca.setText(FrmParametro.IdParametro);
        txtCodP.setText(FrmVistaProveedor.IdProveedor);
        txtOrden.setText(CodVenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        btnAddPro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnDeletePro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtDireccion = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtApe = new javax.swing.JTextField();
        txtCodP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAddCli = new javax.swing.JButton();
        txtNombre1 = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOrden = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btnNuevoCl = new javax.swing.JButton();
        btnGuardarCl = new javax.swing.JButton();
        btnCancelarCl = new javax.swing.JButton();
        btnSalirCl = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducto = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MONTO TOTAL");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(102, 102, 102));
        txtMarca.setText("INGRESE LA MARCA");
        txtMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMarcaMouseEntered(evt);
            }
        });
        add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 140, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MARCA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jdcFecha.setDateFormatString("dd/MM/yyyy");
        add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 120, -1));

        btnAddPro.setBackground(new java.awt.Color(214, 238, 181));
        btnAddPro.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnAddPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/32379_add_plus_icon.png"))); // NOI18N
        btnAddPro.setText("AGREGAR PRODUCTO(S)");
        btnAddPro.setAlignmentY(0.0F);
        btnAddPro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProActionPerformed(evt);
            }
        });
        add(btnAddPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 180, -1));

        jButton1.setText("Clik");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        btnDeletePro.setBackground(new java.awt.Color(238, 186, 178));
        btnDeletePro.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnDeletePro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/7697_fewer_icon.png"))); // NOI18N
        btnDeletePro.setText("MOSTRAR PRODUCTOS");
        btnDeletePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProActionPerformed(evt);
            }
        });
        add(btnDeletePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jPanel3.setBackground(new java.awt.Color(129, 94, 75));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "DATOS DEL PROVEEDOR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, -1));

        txtDNI.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel3.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 120, -1));

        txtApe.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel3.add(txtApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 190, -1));

        txtCodP.setEditable(false);
        txtCodP.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCodP.setText("*******");
        txtCodP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodPMousePressed(evt);
            }
        });
        txtCodP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodPActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOMBRE");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("APELLIDOS");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DIRECCIÓN");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CÓDIGO");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        btnAddCli.setBackground(new java.awt.Color(199, 192, 165));
        btnAddCli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/49576_new_add_plus_user_icon (1).png"))); // NOI18N
        btnAddCli.setText("PROVEEDOR");
        btnAddCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCliActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, 50));

        txtNombre1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel3.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 600, 130));

        txtMonto.setEditable(false);
        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMonto.setText("0.00");
        add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 120, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CÓDIGO DE ORDEN");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        txtOrden.setEditable(false);
        txtOrden.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtOrden.setText("Click para generar COD");
        txtOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtOrdenMousePressed(evt);
            }
        });
        txtOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrdenActionPerformed(evt);
            }
        });
        add(txtOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, -1));

        jPanel11.setBackground(new java.awt.Color(167, 144, 131));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoCl.setBackground(new java.awt.Color(199, 192, 165));
        btnNuevoCl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnNuevoCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/7340574_e-commerce_online_shopping_ui_box package_icon (2).png"))); // NOI18N
        btnNuevoCl.setText("NUEVO");
        jPanel11.add(btnNuevoCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, 42));

        btnGuardarCl.setBackground(new java.awt.Color(199, 192, 165));
        btnGuardarCl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnGuardarCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/285657_floppy_guardar_save_icon (1).png"))); // NOI18N
        btnGuardarCl.setText("GUARDAR");
        btnGuardarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClActionPerformed(evt);
            }
        });
        jPanel11.add(btnGuardarCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, 42));

        btnCancelarCl.setBackground(new java.awt.Color(199, 192, 165));
        btnCancelarCl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnCancelarCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9004715_cross_delete_remove_cancel_icon (1).png"))); // NOI18N
        btnCancelarCl.setText("CANCELAR");
        jPanel11.add(btnCancelarCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 160, 42));

        btnSalirCl.setBackground(new java.awt.Color(199, 192, 165));
        btnSalirCl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnSalirCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/3005766_account_door_exit_logout_icon.png"))); // NOI18N
        btnSalirCl.setText("SALIR");
        jPanel11.add(btnSalirCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 160, 42));

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 240, 260));

        tbProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbProducto);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 620, 150));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FECHA");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Ord.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodPActionPerformed

    private void btnAddCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCliActionPerformed
        ProveedorDTO obj = Bo2.VentaCliente(txtCodP.getText());
        if(obj!=null){
            txtNombre1.setText(obj.getIdProveedor().trim());
            txtApe.setText(obj.getIdPersona().trim());
            txtDireccion.setText(obj.getObservaciones().trim());
            txtDNI.setText(obj.getReferencias().trim());
            System.out.println("no esta vacio");
        }else{
            System.out.println("esta vacio :( ");
        }
    }//GEN-LAST:event_btnAddCliActionPerformed

    private void btnAddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProActionPerformed
    
// TODO add your handling code here:
   try {
            this.Agregar();
        } catch (Exception e) {
            System.out.println("no se puede agregar la venta :(");
        }
        FrmDProd1 p1 = new FrmDProd1();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnAddProActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         FrmParametro p1 = new FrmParametro();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMarcaMouseEntered
    }//GEN-LAST:event_txtMarcaMouseEntered

    private void txtOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdenActionPerformed

    private void txtCodPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodPMousePressed
        FrmVistaProveedor p1 = new FrmVistaProveedor();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_txtCodPMousePressed

    private void txtOrdenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOrdenMousePressed
        CodVenta = Bo.CodigoVenta("Hola");
        txtOrden.setText(CodVenta);        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrdenMousePressed

    private void btnDeleteProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProActionPerformed
             this.limpiarTabla();
            this.Listar();
      txtMonto.setText("S/"+String.valueOf(suma));
    }//GEN-LAST:event_btnDeleteProActionPerformed

    private void btnGuardarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClActionPerformed
           String Mensaje="";
           
           Mensaje = Bo.Actualizar(txtOrden.getText(), suma, jdcFecha.getDate(),txtCodP.getText(),txtMarca.getText(),true);
         System.out.println(Mensaje);
    }//GEN-LAST:event_btnGuardarClActionPerformed
 private void Agregar()throws Exception{
        String Mensaje = Bo.Agregar(txtOrden.getText().trim(), Float.parseFloat(txtMonto.getText()),
               txtCodP.getText(),txtMarca.getText(),true);
        System.out.println(Mensaje);
    }
   private void limpiarTabla() {
        dtm2 = (DefaultTableModel) tbProducto.getModel();
        dtm2.getDataVector().removeAllElements();
        tbProducto.removeAll();
    }
      private void Listar() {  //venta
        dtm2 = (DefaultTableModel) tbProducto.getModel();
        Object[] obj = new Object[5];
        for (DetalleProductoDTO a : VentaDBO.listar(txtOrden.getText())) {
            obj[0] = a.getIdDeatelleProducto().trim();
            obj[4] = a.getIdProducto().trim();
            obj[1] = a.getCantidad();     
            obj[2] = a.getPrecioComprar();
            suma += a.getTotal();
            obj[3] = a.getTotal();
            dtm2.addRow(obj);
        }
    }
public static String CodVenta;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCli;
    private javax.swing.JButton btnAddPro;
    private javax.swing.JButton btnCancelarCl;
    private javax.swing.JButton btnDeletePro;
    private javax.swing.JButton btnGuardarCl;
    private javax.swing.JButton btnNuevoCl;
    private javax.swing.JButton btnSalirCl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTable tbProducto;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtCodP;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtOrden;
    // End of variables declaration//GEN-END:variables
}
