/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author RENZO
 */
public class FrmReportePed extends javax.swing.JPanel {

    /**
     * Creates new form FrmReportePed
     */
    public FrmReportePed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rdbVenEs = new javax.swing.JRadioButton();
        dtcFecha = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        rdbTodVentas = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(129, 94, 75));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "BÚSQUEDA DE PEDIDOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Symbol", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdbVenEs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdbVenEs.setForeground(new java.awt.Color(255, 255, 255));
        rdbVenEs.setText("VENTA ESPECÍFICA");
        rdbVenEs.setOpaque(false);
        jPanel1.add(rdbVenEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        dtcFecha.setDateFormatString("dd/MM/ yyyy");
        jPanel1.add(dtcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 160, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 150, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 150, -1));

        rdbTodVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdbTodVentas.setForeground(new java.awt.Color(255, 255, 255));
        rdbTodVentas.setText("TODAS LAS VENTAS");
        rdbTodVentas.setOpaque(false);
        jPanel1.add(rdbTodVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("DESDE");
        jRadioButton1.setOpaque(false);
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 20, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ELIJA EL RANGO DE LA FECHA DEL PEDIDO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 740, 140));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 740, 190));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 740, 170));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(129, 94, 75));
        jLabel3.setText("DETALLE DE PEDIDOS");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 190, 30));

        btnMenu.setBackground(new java.awt.Color(199, 192, 165));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/2203529_app_block_menu_setting_tile_icon.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 50, 50));

        menu.setBackground(new java.awt.Color(129, 94, 75));
        menu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        menu.setForeground(new java.awt.Color(129, 94, 75));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setBackground(new java.awt.Color(199, 192, 165));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/66923_date_search_icon.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        menu.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 42));

        btnReport.setBackground(new java.awt.Color(199, 192, 165));
        btnReport.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/1622837_analytics_docs_documents_graph_pdf_icon (2).png"))); // NOI18N
        btnReport.setText("REPORTE");
        menu.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 42));

        btnSalir.setBackground(new java.awt.Color(199, 192, 165));
        btnSalir.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9161303_log_out_input_access_security_icon.png"))); // NOI18N
        btnSalir.setText("SALIR");
        menu.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 42));

        add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 190, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DETALLE DE PRODUCTO.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
      /*  int posicion = btnMenu.getX();
        if(posicion < 980){
            Animacion.Animacion.mover_derecha(830, 980, 2, 2, btnMenu);
            Animacion.Animacion.mover_derecha(880, 1230, 2, 2, menu);
        }else{
            Animacion.Animacion.mover_izquierda(980,830, 4, 3, btnMenu);
            Animacion.Animacion.mover_izquierda(1230, 880, 3, 4, menu);

        }*/
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser dtcFecha;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel menu;
    private javax.swing.JRadioButton rdbTodVentas;
    private javax.swing.JRadioButton rdbVenEs;
    // End of variables declaration//GEN-END:variables
}
