/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BussinessObject.PersonaBO;
import BussinessObject.UsuarioBO;
import DataTransferObject.PersonaDTO;
import DataTransferObject.UsuarioDTO;
import Implementacion.IDaoGeneral;
import static Presentacion.DashBoard.content;
import Type.BaseDatos;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class FrmUsuario extends javax.swing.JPanel {
    BaseDatos Gestor;
     IDaoGeneral ClienteDao;
     UsuarioBO Bo;
     PersonaBO Bo2;
    public FrmUsuario() {
        initComponents();
                ClienteDao = FrmLogin.dao;
        Gestor = FrmLogin.base;
        Bo = new UsuarioBO(ClienteDao.UsuarioClass(Gestor));
        Bo2 = new PersonaBO(ClienteDao.PersonaClass(Gestor));
        txtCodigoPersona.setText(FrmVistaUser1.IdPersona);
        txtCodigoUsuario.setText(FrmVistaUser1.IdUsuario);       
        cbxNivel.setSelectedItem(FrmVistaUser1.TipoD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificarCl = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalirCl = new javax.swing.JButton();
        Text4 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        text5 = new javax.swing.JLabel();
        text9 = new javax.swing.JLabel();
        text8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text10 = new javax.swing.JLabel();
        text11 = new javax.swing.JLabel();
        text12 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCodigoUsuario = new javax.swing.JTextField();
        txtCodigoPersona = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        cbxNivel = new javax.swing.JComboBox<>();
        txtNumeroDoc = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        cbxtipoDocumento2 = new javax.swing.JComboBox<>();
        jcbEstado = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        rbtnMasculino = new javax.swing.JRadioButton();
        rbtnFemenino = new javax.swing.JRadioButton();
        jdcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();
        cbxTipoDocumento = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(167, 144, 131));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnListar.setBackground(new java.awt.Color(163, 149, 126));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/49576_new_add_plus_user_icon.png"))); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(163, 149, 126));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/285657_floppy_guardar_save_icon.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(163, 149, 126));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9004715_cross_delete_remove_cancel_icon.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");

        btnModificarCl.setBackground(new java.awt.Color(163, 149, 126));
        btnModificarCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/8726304_refresh_icon.png"))); // NOI18N
        btnModificarCl.setText("Extraer datos");
        btnModificarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(163, 149, 126));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/352303_delete_icon.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalirCl.setBackground(new java.awt.Color(163, 149, 126));
        btnSalirCl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/8725805_exit_icon.png"))); // NOI18N
        btnSalirCl.setText("ACTUALIZAR");
        btnSalirCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirClActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarCl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(btnSalirCl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirCl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 410, 140));

        Text4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text4.setForeground(new java.awt.Color(255, 255, 255));
        Text4.setText("TIPO DE USER");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        Text3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setText("NOMBRE");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("CÓDIGO");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FECHA DE NACIMIENTO");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("INGRESE EL NOMBRE");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 280, -1));

        text5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text5.setForeground(new java.awt.Color(255, 255, 255));
        text5.setText("TIPO DE DOCUMENTO");
        add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        text9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text9.setForeground(new java.awt.Color(255, 255, 255));
        text9.setText("NÚMERO DE DOC.");
        add(text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        text8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text8.setForeground(new java.awt.Color(255, 255, 255));
        text8.setText("ESTADO");
        add(text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("N° DE PERSONA");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        text10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text10.setForeground(new java.awt.Color(255, 255, 255));
        text10.setText("CELULAR");
        add(text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        text11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text11.setForeground(new java.awt.Color(255, 255, 255));
        text11.setText("CORREO");
        add(text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        text12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        text12.setForeground(new java.awt.Color(255, 255, 255));
        text12.setText("DIRECCIÓN");
        add(text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        txtCelular.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(102, 102, 102));
        txtCelular.setText("INGRESE EL NÚMERO DE CEL.");
        txtCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCelularMousePressed(evt);
            }
        });
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 280, -1));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreo.setText("INGRESE EL CORREO");
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 280, -1));

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(102, 102, 102));
        txtDireccion.setText("INGRESE LA DIRECCIÓN");
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionMousePressed(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 220, -1));

        txtCodigoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCodigoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoUsuario.setText("INGRESE EL CÓDIGO");
        txtCodigoUsuario.setEnabled(false);
        txtCodigoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoUsuarioMousePressed(evt);
            }
        });
        txtCodigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoUsuarioActionPerformed(evt);
            }
        });
        add(txtCodigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 230, -1));

        txtCodigoPersona.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtCodigoPersona.setEnabled(false);
        txtCodigoPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoPersonaMousePressed(evt);
            }
        });
        add(txtCodigoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 110, -1));

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(102, 102, 102));
        txtApellido.setText("INGRESE LOS APELLIDOS");
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 280, -1));

        cbxNivel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Administrador", "Empleado" }));
        cbxNivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxNivelMousePressed(evt);
            }
        });
        add(cbxNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 190, -1));

        txtNumeroDoc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNumeroDoc.setForeground(new java.awt.Color(102, 102, 102));
        txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
        txtNumeroDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroDocMousePressed(evt);
            }
        });
        add(txtNumeroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 160, -1));

        txtSueldo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtSueldo.setForeground(new java.awt.Color(102, 102, 102));
        txtSueldo.setText("INGRESE EL SUELDO");
        txtSueldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSueldoMousePressed(evt);
            }
        });
        add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 120, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setText("INGRESE LA CONTRASEÑA");
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 270, -1));

        cbxtipoDocumento2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cbxtipoDocumento2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DNI", "CARNET DE EXTRANJERÍA", "PASAPORTE" }));
        cbxtipoDocumento2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxtipoDocumento2MousePressed(evt);
            }
        });
        add(cbxtipoDocumento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 160, -1));

        jcbEstado.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(255, 255, 255));
        jcbEstado.setText("ACTIVO");
        add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, -1));

        jPanel2.setBackground(new java.awt.Color(167, 144, 131));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "SEXO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        rbtnMasculino.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbtnMasculino.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMasculino.setText("Masculino");

        rbtnFemenino.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbtnFemenino.setForeground(new java.awt.Color(255, 255, 255));
        rbtnFemenino.setText("Femenino");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnMasculino)
                .addGap(18, 18, 18)
                .addComponent(rbtnFemenino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMasculino)
                    .addComponent(rbtnFemenino))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 190, 60));

        jdcFechaNacimiento.setDateFormatString("dd/MM/yyyy");
        add(jdcFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 160, -1));

        jSeparator1.setBackground(new java.awt.Color(235, 224, 179));
        jSeparator1.setForeground(new java.awt.Color(235, 224, 179));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 20, 230));

        jSeparator2.setBackground(new java.awt.Color(235, 224, 179));
        jSeparator2.setForeground(new java.awt.Color(235, 224, 179));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 20, 230));

        Text5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text5.setForeground(new java.awt.Color(255, 255, 255));
        Text5.setText("APELLIDOS");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        Text6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text6.setForeground(new java.awt.Color(255, 255, 255));
        Text6.setText("CONTRASEÑA");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, -1));

        Text7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        Text7.setForeground(new java.awt.Color(255, 255, 255));
        Text7.setText("SUELDO");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        cbxTipoDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario 1.png"))); // NOI18N
        add(cbxTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNombre.getText()).equals("INGRESE EL NOMBRE")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        if (txtCodigoUsuario.getText().isEmpty()) {
            txtCodigoUsuario.setText("INGRESE EL CÓDIGO");
            txtCodigoUsuario.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtCelular.getText().isEmpty()) {
            txtCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
         if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE LA CONTRASEÑA");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE EL SUELDO");
            txtNumeroDoc.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtCelularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCelularMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtCelular.getText()).equals("INGRESE EL NÚMERO DE CEL.")) {
            txtCelular.setText("");
            txtCelular.setForeground(Color.black);
        }
        if (txtCodigoUsuario.getText().isEmpty()) {
            txtCodigoUsuario.setText("INGRESE EL CÓDIGO");
            txtCodigoUsuario.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
         if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE LA CONTRASEÑA");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE EL SUELDO");
            txtNumeroDoc.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCelularMousePressed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtCorreo.getText()).equals("INGRESE EL CORREO")) {
            txtCorreo.setText("");
            txtCorreo.setForeground(Color.black);
        }
        if (txtCodigoUsuario.getText().isEmpty()) {
            txtCodigoUsuario.setText("INGRESE EL CÓDIGO");
            txtCodigoUsuario.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtCelular.getText().isEmpty()) {
            txtCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtCelular.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
         if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE LA CONTRASEÑA");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE EL SUELDO");
            txtNumeroDoc.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtDireccion.getText()).equals("INGRESE LA DIRECCIÓN")) {
            txtDireccion.setText("");
            txtDireccion.setForeground(Color.black);
        }
        if (txtCodigoUsuario.getText().isEmpty()) {
            txtCodigoUsuario.setText("INGRESE EL CÓDIGO");
            txtCodigoUsuario.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }

        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtCelular.getText().isEmpty()) {
            txtCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
         if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE LA CONTRASEÑA");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE EL SUELDO");
            txtNumeroDoc.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtDireccionMousePressed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCodigoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoUsuarioMousePressed
     // txtCodigoPersona.setText(this.CodigoPersona());
     txtCodigoUsuario.setText(this.CodigoCliente());
        if (String.valueOf(txtCodigoUsuario.getText()).equals("INGRESE EL CÓDIGO")) {
            txtCodigoUsuario.setText("");
            txtCodigoUsuario.setForeground(Color.black);
        }
        txtNumeroDoc.setText("");
        txtNombre.setText("");
        txtCorreo.setText("");
        txtCelular.setText("");
        txtDireccion.setText("");
        txtApellido.setText("");
        cbxtipoDocumento2.setSelectedIndex(0);
        jdcFechaNacimiento.setDateFormatString("DD-MM-AA");
        txtPassword.setText("");
        txtSueldo.setText("");
        cbxNivel.setSelectedIndex(0);
        jcbEstado.setSelected(true);
        
    }//GEN-LAST:event_txtCodigoUsuarioMousePressed

    private void txtCodigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoUsuarioActionPerformed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtApellido.getText()).equals("INGRESE LOS APELLIDOS")) {
            txtApellido.setText("");
            txtApellido.setForeground(Color.black);
        }
        if (txtCodigoUsuario.getText().isEmpty()) {
            txtCodigoUsuario.setText("INGRESE EL CÓDIGO");
            txtCodigoUsuario.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtCelular.getText().isEmpty()) {
            txtCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
         if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE LA CONTRASEÑA");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE EL SUELDO");
            txtNumeroDoc.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_txtApellidoMousePressed

    private void cbxNivelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxNivelMousePressed
        // TODO add your handling code here:
        txtNumeroDoc.setVisible(true);
    }//GEN-LAST:event_cbxNivelMousePressed

    private void txtNumeroDocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroDocMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNumeroDoc.getText()).equals("INGRESE NUMERO DE DOC.")) {
            txtNumeroDoc.setText("");
            txtNumeroDoc.setForeground(Color.black);
        }
        if (txtCodigoUsuario.getText().isEmpty()) {
            txtCodigoUsuario.setText("INGRESE EL CÓDIGO");
            txtCodigoUsuario.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }      
        if (txtCelular.getText().isEmpty()) {
            txtCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
         if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE LA CONTRASEÑA");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE EL SUELDO");
            txtNumeroDoc.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNumeroDocMousePressed

    private void cbxtipoDocumento2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxtipoDocumento2MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxtipoDocumento2MousePressed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNumeroDoc.getText()).equals("INGRESE EL SUELDO")) {
            txtNumeroDoc.setText("");
            txtNumeroDoc.setForeground(Color.black);
        }
        if (txtCodigoUsuario.getText().isEmpty()) {
            txtCodigoUsuario.setText("INGRESE EL CÓDIGO");
            txtCodigoUsuario.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtCelular.getText().isEmpty()) {
            txtCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE LA CONTRASEÑA");
            txtNumeroDoc.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPasswordMousePressed

    private void txtSueldoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSueldoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtNumeroDoc.getText()).equals("INGRESE LA CONTRASEÑA")) {
            txtNumeroDoc.setText("");
            txtNumeroDoc.setForeground(Color.black);
        }
        if (txtCodigoUsuario.getText().isEmpty()) {
            txtCodigoUsuario.setText("INGRESE EL CÓDIGO");
            txtCodigoUsuario.setForeground(Color.gray);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("INGRESE EL NOMBRE");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApellido.getText().isEmpty()) {
            txtApellido.setText("INGRESE LOS APELLIDOS");
            txtApellido.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE NUMERO DE DOC.");
            txtNumeroDoc.setForeground(Color.gray);
        }
        if (txtCelular.getText().isEmpty()) {
            txtCelular.setText("INGRESE EL NÚMERO DE CEL.");
            txtCelular.setForeground(Color.gray);
        }
        if (txtCorreo.getText().isEmpty()) {
            txtCorreo.setText("INGRESE EL CORREO");
            txtCorreo.setForeground(Color.gray);
        }
        if (txtDireccion.getText().isEmpty()) {
            txtDireccion.setText("INGRESE LA DIRECCIÓN");
            txtDireccion.setForeground(Color.gray);
        }
        if (txtNumeroDoc.getText().isEmpty()) {
            txtNumeroDoc.setText("INGRESE EL SUELDO");
            txtNumeroDoc.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSueldoMousePressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            this.AgregarCliente();
            JOptionPane.showMessageDialog(null, "Usuario agregado con exito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println("no funciona :(");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        FrmVistaUser1 p1 = new FrmVistaUser1();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnModificarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClActionPerformed
          this.Buscar(txtCodigoUsuario.getText());
     this.BuscarPersona(txtCodigoPersona.getText());
    }//GEN-LAST:event_btnModificarClActionPerformed

    private void btnSalirClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirClActionPerformed
             try {
            this.ActualizarCliente();
            JOptionPane.showMessageDialog(null, "Cliente actualizado con exito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println("no funciona :(");
        }
    }//GEN-LAST:event_btnSalirClActionPerformed

    private void txtCodigoPersonaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoPersonaMousePressed
        txtCodigoPersona.setText(this.CodigoPersona());
    }//GEN-LAST:event_txtCodigoPersonaMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            String x = this.Eliminar();
            String y = this.EliminarPersona();
            JOptionPane.showMessageDialog(null, x + " | " + y, "Mensaje", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificarCl;
    private javax.swing.JButton btnSalirCl;
    private javax.swing.JComboBox<String> cbxNivel;
    private javax.swing.JLabel cbxTipoDocumento;
    private javax.swing.JComboBox<String> cbxtipoDocumento2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox jcbEstado;
    private com.toedter.calendar.JDateChooser jdcFechaNacimiento;
    private javax.swing.JRadioButton rbtnFemenino;
    private javax.swing.JRadioButton rbtnMasculino;
    private javax.swing.JLabel text10;
    private javax.swing.JLabel text11;
    private javax.swing.JLabel text12;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel text9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigoPersona;
    private javax.swing.JTextField txtCodigoUsuario;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroDoc;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
        private String Estado(boolean o){
        if(o){
            return "Activo";
        }
        return "Inactivo";
    }
        private String ControlParametro(String codigo) {
        if (codigo.equalsIgnoreCase("DNI")) {
            return "Parametro_01";
        } else {
            if (codigo.equalsIgnoreCase("CARNET DE EXTRANJERIA")) {
                return "Parametro_02";
            } else {
                    return "Parametro_03";
            }
        }
    }
      private String ControlParametro2(String codigo) {
        if (codigo.equalsIgnoreCase("Administrador")) {
            return "Parametro_11";
        } else {
            if (codigo.equalsIgnoreCase("Empleado")) {
                return "Parametro_12";
            } else {
                    return "Parametro_13";
            }
        }
    }
    private String Genero(boolean o) {
        if (o) {
            return "Masculino";
        }
        return "Femenino";
    }
        private String CodigoPersona(){
        return Bo2.CodigoPersona();
    }
    private String CodigoCliente(){
        return Bo.CodigoParametro();
    }
        private String EliminarPersona()throws Exception{
        String Mensaje;
        Mensaje= Bo2.Eliminar(txtCodigoPersona.getText().trim());
        return Mensaje;
    }
    private String Eliminar() throws Exception {
        String Mensaje;
        Mensaje = Bo.Eliminar(txtCodigoUsuario.getText().trim());
        return Mensaje;
    }
        private void ActualizarCliente() throws Exception {
        String Mensaje1;
        String Mensaje2;
        System.out.println(txtCodigoPersona.getText());
        Mensaje2 = Bo2.Actualizar(txtCodigoPersona.getText(), txtNombre.getText(), txtApellido.getText(), txtNumeroDoc.getText(), txtCelular.getText(), txtCorreo.getText(),
                this.Genero(rbtnMasculino.isSelected()), jdcFechaNacimiento.getDate(), txtDireccion.getText(), this.ControlParametro(cbxtipoDocumento2.getSelectedItem().toString()), this.Estado(jcbEstado.isSelected()));
        System.out.println(Mensaje2);
        Mensaje1 = Bo.Actualizar(txtCodigoUsuario.getText(), txtCodigoPersona.getText(), Float.parseFloat(txtSueldo.getText()), txtPassword.getText(), this.ControlParametro2(cbxNivel.getSelectedItem().toString()),jcbEstado.isSelected());
        System.out.println(Mensaje1);
    }
      private void AgregarCliente() throws Exception {
        String Mensaje1;
        String Mensaje2;
        System.out.println(txtCodigoPersona.getText());
        Mensaje2 = Bo2.Agregar(txtCodigoPersona.getText(), txtNombre.getText(), txtApellido.getText(), txtNumeroDoc.getText(), txtCelular.getText(), txtCorreo.getText(),
                this.Genero(rbtnMasculino.isSelected()), jdcFechaNacimiento.getDate(), txtDireccion.getText(), this.ControlParametro(cbxtipoDocumento2.getSelectedItem().toString()), this.Estado(jcbEstado.isSelected()));
        System.out.println(Mensaje2);
        Mensaje1 = Bo.Agregar(txtCodigoUsuario.getText(),txtCodigoPersona.getText(), Float.parseFloat(txtSueldo.getText()), txtPassword.getText(),this.ControlParametro2(cbxNivel.getSelectedItem().toString()), jcbEstado.isSelected());
        JOptionPane.showMessageDialog(null, Mensaje1, "Mensaje", JOptionPane.WARNING_MESSAGE);
    }
          private void BuscarPersona(String Id){
       PersonaDTO obj = Bo2.buscar(Id);
       txtNombre.setText(obj.getNombre());
       txtApellido.setText(obj.getApellido());
       txtCorreo.setText(obj.getCorreo());
       txtCelular.setText(obj.getCelular());
       txtNumeroDoc.setText(obj.getNumeroDucumento());
       jdcFechaNacimiento.setDate(obj.getFechaNac());
       rbtnMasculino.setSelected(obj.getGenero().equals("Masculino"));
       rbtnFemenino.setSelected(obj.getGenero().equals("Femenino"));
       txtDireccion.setText(obj.getDireccion());
        System.out.println(obj.getIdParametro());
       
    }
    private void Buscar(String Id) {
        UsuarioDTO obj = Bo.Buscar(Id);
        txtSueldo.setText(String.valueOf(obj.getSueldo()));
        txtPassword.setText(obj.getPassword());
        jcbEstado.setSelected(obj.isEstado());
        cbxNivel.setSelectedItem(obj.getIdParametro());
    }
}
