/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

import BussinessObject.DetalleVentaBO;
import BussinessObject.ProductoBO;
import DataTransferObject.ProductoDTO;
import Implementacion.IDaoGeneral;
import static Presentacion.DashBoard.content;
import Type.BaseDatos;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FrmVistaProd extends javax.swing.JPanel {

        BaseDatos Gestor;
    IDaoGeneral ProductoDao;
    ProductoBO Bo;
    DetalleVentaBO Venta;
    DefaultTableModel dtm = new DefaultTableModel();
    public FrmVistaProd() {
        initComponents();
         ProductoDao = FrmLogin.dao;
        Gestor =FrmLogin.base;
        Bo = new ProductoBO(ProductoDao.ProductoClass(Gestor));
        Venta = new DetalleVentaBO(ProductoDao.DetalleVentaClass(Gestor));
            txtCodigoVenta.setText(FrmNuevaVenta.CodVenta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPrecio = new javax.swing.JTextField();
        txtCodigoProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoVenta = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducto2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(129, 94, 75));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "DATOS DE LA VENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrecio.setEditable(false);
        txtPrecio.setText("........");
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 106, -1));

        txtCodigoProducto.setEditable(false);
        txtCodigoProducto.setText("-----------------------");
        jPanel1.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 75, 132, -1));

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 106, -1));

        txtStock.setEditable(false);
        txtStock.setText(".....");
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, -1));

        txtDescuento.setEditable(false);
        txtDescuento.setText("NO HABILITADO");
        jPanel1.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 114, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CODIGO DE PEDIDO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 38, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CODIGO DE PRODUCTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 78, -1, -1));

        txtNombreProducto.setEditable(false);
        txtNombreProducto.setText("*****************************************************");
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 130, 341, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CANTIDAD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("IMPORTE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        txtCodigoVenta.setEditable(false);
        txtCodigoVenta.setText("Codigo de venta");
        jPanel1.add(txtCodigoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 35, 132, -1));

        txtTotal.setEditable(false);
        txtTotal.setText("$$$$$");
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 106, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRECIO UNITARIO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("STOCK");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DESCUENTO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 390, 310));

        jButton1.setBackground(new java.awt.Color(199, 192, 165));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/115695_magnifying glass_zoom_find_search_icon.png"))); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.setAlignmentY(0.0F);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 133, 110, 30));

        buscar.setForeground(new java.awt.Color(102, 102, 102));
        buscar.setText("Search...");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarMousePressed(evt);
            }
        });
        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 133, 450, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 0, 0))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(214, 238, 181));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/32379_add_plus_icon.png"))); // NOI18N
        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 35, 134, 31));

        jButton3.setBackground(new java.awt.Color(248, 176, 191));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9004715_cross_delete_remove_cancel_icon (1).png"))); // NOI18N
        jButton3.setText("CANCELAR");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 73, 134, 31));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 170, 130));

        tbProducto2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 204)));
        tbProducto2.setFont(new java.awt.Font("Gadugi", 1, 10)); // NOI18N
        tbProducto2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Stock", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProducto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbProducto2MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbProducto2);
        if (tbProducto2.getColumnModel().getColumnCount() > 0) {
            tbProducto2.getColumnModel().getColumn(0).setPreferredWidth(130);
            tbProducto2.getColumnModel().getColumn(1).setPreferredWidth(500);
            tbProducto2.getColumnModel().getColumn(2).setPreferredWidth(80);
            tbProducto2.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 580, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vista Product.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.limpiarTabla();
       this.Listar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMousePressed
        // TODO add your handling code here:
        if (String.valueOf(buscar.getText()).equals("Search...")) {
            buscar.setText("");
            buscar.setForeground(Color.black);
        }
    }//GEN-LAST:event_buscarMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
            String x = this.Agregar();
            JOptionPane.showMessageDialog(null, x);
        
        /*
        FrmNuevaVenta p1 = new FrmNuevaVenta();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbProducto2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProducto2MousePressed
        int fila = tbProducto2.getSelectedRow();
      if(fila ==-1){
          JOptionPane.showMessageDialog(null, "seleccionar correctamente");
      }else{
         txtCodigoProducto.setText(tbProducto2.getValueAt(fila, 0).toString());
         txtNombreProducto.setText(tbProducto2.getValueAt(fila, 1).toString());
         txtStock.setText(tbProducto2.getValueAt(fila, 2).toString());
         txtPrecio.setText(tbProducto2.getValueAt(fila, 3).toString());
      }
      txtCantidad.setText("");
      txtTotal.setText("");
    }//GEN-LAST:event_tbProducto2MousePressed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
       float total=0;
       try {
            int y = Integer.parseInt(txtCantidad.getText());
            float precio = Float.parseFloat(txtPrecio.getText());
            total = y*precio;
          
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "DEBE INGRESAR DATOS NUMERICOS", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
          txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_txtCantidadKeyPressed

    public String Agregar(){
        String Estado = Venta.Agregar(txtCodigoVenta.getText(), txtCodigoProducto.getText(),Integer.parseInt( txtCantidad.getText().trim()), Float.parseFloat(txtTotal.getText()), 0.00f);
        return Estado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProducto2;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtCodigoVenta;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
   private void limpiarTabla() {
        dtm = (DefaultTableModel) tbProducto2.getModel();
        dtm.getDataVector().removeAllElements();
        tbProducto2.removeAll();
    }
      private void Listar() {  //venta
        dtm = (DefaultTableModel) tbProducto2.getModel();
        Object[] obj = new Object[4];
        for (ProductoDTO a : Bo.listarProductoVenta()) {
            obj[0] = a.getIdProducto().trim();
            obj[1] = a.getNombre().trim();
            obj[2] = a.getStock();     
            obj[3] = a.getPrecioV();
            dtm.addRow(obj);
        }
    }
}
