/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;
import BussinessObject.UsuarioBO;
import DataTransferObject.UsuarioDTO;
import Implementacion.IDaoGeneral;
import static Presentacion.DashBoard.content;
import Type.BaseDatos;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RENZO
 */
public class FrmVistaUser1 extends javax.swing.JPanel {

     DefaultTableModel dtm = new DefaultTableModel();
     BaseDatos Gestor;
     IDaoGeneral ClienteDao;
     UsuarioBO Bo;
     public static String IdPersona;
     public static String IdUsuario;
     public static String TipoD;
     public static String IdUsuario2;
    public FrmVistaUser1() {
        ClienteDao = FrmLogin.dao;
        Gestor = FrmLogin.base;
        Bo = new UsuarioBO(ClienteDao.UsuarioClass(Gestor));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuario = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbUsuarioMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuario);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 490, 450));

        jButton1.setBackground(new java.awt.Color(163, 149, 126));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/115695_magnifying glass_zoom_find_search_icon.png"))); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.setAlignmentY(0.0F);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 110, 30));

        buscar.setForeground(new java.awt.Color(102, 102, 102));
        buscar.setText("Search...");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarMousePressed(evt);
            }
        });
        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 290, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/32379_add_plus_icon.png"))); // NOI18N
        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VistaU.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            this.limpiarTabla();
            Listar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMousePressed
        // TODO add your handling code here:
        if (String.valueOf(buscar.getText()).equals("Search...")) {
            buscar.setText("");
            buscar.setForeground(Color.black);
        }
    }//GEN-LAST:event_buscarMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       int fila = tbUsuario.getSelectedRow();
       IdUsuario2 = tbUsuario.getValueAt(fila,0).toString();
           FrmNuevaVenta p1 = new FrmNuevaVenta();
           p1.setSize(1070, 630);
           p1.setLocation(0, 0);

           content.removeAll();
           content.add(p1, BorderLayout.CENTER);
           content.revalidate();
           content.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuarioMousePressed
      int fila = tbUsuario.getSelectedRow();
      int x =  JOptionPane.showConfirmDialog(null, "Desea actualizar la informacion?", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
      if(x==0){
          IdUsuario = tbUsuario.getValueAt(fila, 0).toString();
          IdPersona =tbUsuario.getValueAt(fila, 1).toString();
          TipoD = tbUsuario.getValueAt(fila, 2).toString();
         this.hola();
      }else{
          System.out.println("hola por aqui");
      }
    }//GEN-LAST:event_tbUsuarioMousePressed
    private void Listar(){
        dtm = (DefaultTableModel)tbUsuario.getModel();
                Object[] obj = new Object[5];
         for(UsuarioDTO a:Bo.listar()){
             System.out.println("hola------");
            obj[0] = a.getIdUsuario().trim();
            obj[1] = a.getIdPersona().trim();
            obj[2] = a.getNivel().trim();
            obj[3] = a.getSueldo();
            obj[4] = a.getEstadoTxt().trim();
            dtm.addRow(obj);
         }
    }    
    private void limpiarTabla() {
        dtm = (DefaultTableModel) tbUsuario.getModel();
        dtm.getDataVector().removeAllElements();
        tbUsuario.removeAll();
    }
        private void hola(){
                    FrmUsuario p1 = new FrmUsuario();
        p1.setSize(1070, 630);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbUsuario;
    // End of variables declaration//GEN-END:variables
}
